### ISSUE TITLE
Is is possible to configure this to deploy to the testnet?

### ISSUE THREAD

**Issue by llewenyerg** [WhenLamboMoon/docker-zen-node#1]
I'm not sure if challenges are being sent to mainnet nodes, and I wanted to set this up on the testnet at first (if possible).

**Comment by 333miiko** [comment]
@llewenyerg currently this will setup your node for testnet.

See this line https://github.com/WhenLamboMoon/docker-zen-node/blob/master/install.sh#L22

When we move to mainnet I'll update this so people can transition to mainnet. Alternatively you can just edit that line to be `testnet=0`
