### ISSUE TITLE
ready for launch??  :)

### ISSUE THREAD

**Issue by phobos777** [WhenLamboMoon/docker-zen-node#10]
let us know when you guys are ready for launch.  :)   once we have a final code i can go production with let me know.  i'll tip you guys to.  :)   -P

**Comment by 333miiko** [comment]
I'll update it shortly after I run some of my own tests, it's a very quick change to go to mainnet

**Comment by 333miiko** [comment]
I've updated the code so you should now be able to deploy to mainnet now :)

**Comment by phobos777** [comment]
Oh wonderful!!  your the best.  i'm on it!  i'll let you know how it goes

**Comment by 333miiko** [comment]
Just note mainnet isn't up yet, I think there's a maintenance for another 2 more hours.

**Comment by 333miiko** [comment]
I have deployed a few nodes on mainnet now without any issues, this should be good to go :)

**Comment by phobos777** [comment]
okay loading now! for first tests!  :)
