### ISSUE TITLE
Is Docker running?

### ISSUE THREAD

**Issue by phobos777** [WhenLamboMoon/docker-zen-node#100]
@333miiko   hi!  i'm getting a new error sporadically these days.   here is the output when running secnodetracker:

root@localhost: docker logs -f zen-secnodetracker
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
root@localhost:

let me know your thoughts .  thanks!

**Comment by 333miiko** [comment]
Sounds like your docker daemon may be crashing. Are you ok on free memory and disk space?

Could you also try updating your server see if there's a docker patch that may be available:

```
apt-get update && apt-get upgrade -y
```

**Comment by phobos777** [comment]
maybe this would help:.   one installing the install.sh script i'm getting the error right away now:  

## Installing the ZenCash node...

#########################
fqdn: my details
email: my email
stakeaddr: my staking addresess
#########################

## Populating apt-get cache...

Hit:1 http://mirrors.linode.com/ubuntu xenial InRelease
Hit:2 http://mirrors.linode.com/ubuntu xenial-updates InRelease
Hit:3 http://mirrors.linode.com/ubuntu xenial-backports InRelease
Get:4 http://security.ubuntu.com/ubuntu xenial-security InRelease [107 kB]
Hit:5 http://ppa.launchpad.net/certbot/certbot/ubuntu xenial InRelease
Hit:6 https://download.docker.com/linux/ubuntu xenial InRelease
Fetched 107 kB in 0s (109 kB/s)
Reading package lists... Done

## Installing packages required for setup...

Synchronizing state of docker.service with SysV init with /lib/systemd/systemd-sysv-install...
Executing /lib/systemd/systemd-sysv-install enable docker
Job for docker.service failed because the control process exited with error code. See "systemctl status docker.service" and "journalctl -xe" for details.

## Creating the docker mount directories...


## Installing acme container service...

A dependency job for acme-sh.service failed. See 'journalctl -xe' for details.

## Waiting for acme-sh to come up...

Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
..
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
..

**Comment by 333miiko** [comment]
That's because docker.sock is a unix socket. 

Could you try post the output of:

```
systemctl status -l docker.service
```

**Comment by phobos777** [comment]
okay.  here is the output.  and thank you for helping!!!!!!!!!!!

root@localhost:~# systemctl status -l docker.service
● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sat 2018-08-11 12:38:01 UTC; 5s ago
     Docs: https://docs.docker.com
  Process: 4154 ExecStart=/usr/bin/dockerd -H fd:// $DOCKER_OPTS (code=exited, status=1/FAILURE)
 Main PID: 4154 (code=exited, status=1/FAILURE)

Aug 11 12:38:01 localhost dockerd[4154]: time="2018-08-11T12:38:01.887769867Z" level=info msg="libcontainerd: new containerd process, pid: 4158"
Aug 11 12:38:01 localhost dockerd[4154]: time="2018-08-11T12:38:01.917920200Z" level=error msg="There are no more loopback devices available."
Aug 11 12:38:01 localhost dockerd[4154]: time="2018-08-11T12:38:01.918587415Z" level=error msg="[graphdriver] prior storage driver devicemapper failed: loopback attach failed"
Aug 11 12:38:01 localhost dockerd[4154]: Error starting daemon: error initializing graphdriver: loopback attach failed
Aug 11 12:38:01 localhost systemd[1]: docker.service: Main process exited, code=exited, status=1/FAILURE
Aug 11 12:38:01 localhost systemd[1]: Failed to start Docker Application Container Engine.
Aug 11 12:38:01 localhost systemd[1]: docker.service: Unit entered failed state.
Aug 11 12:38:01 localhost systemd[1]: docker.service: Failed with result 'exit-code'.
Aug 11 12:38:01 localhost systemd[1]: docker.service: Start request repeated too quickly.
Aug 11 12:38:01 localhost systemd[1]: Failed to start Docker Application Container Engine.
root@localhost:~#

**Comment by phobos777** [comment]
and df:

root@localhost:~# df
Filesystem     1K-blocks     Used Available Use% Mounted on
/dev/root       30455804 14830688  14062084  52% /
devtmpfs         1014344        0   1014344   0% /dev
tmpfs            1016648        0   1016648   0% /dev/shm
tmpfs            1016648     8516   1008132   1% /run
tmpfs               5120        0      5120   0% /run/lock
tmpfs            1016648        0   1016648   0% /sys/fs/cgroup
tmpfs             203332        0    203332   0% /run/user/0
root@localhost:~#

**Comment by 333miiko** [comment]
Is this a different provider? Or an existing server

**Comment by 333miiko** [comment]
This is the error here " Error starting daemon: error initializing graphdriver: loopback attach failed" but it's weird that it would show up on an existing server

**Comment by phobos777** [comment]
it's an existing server.  Linode hoster.   seems to be isolated there,  and this is about five servers now.  eek!  LOL

**Comment by phobos777** [comment]
and p.s. they were impacted today without upgrading or anything.  so meaning, it likely could of been maintaince or hardware upgrade work from last night.

**Comment by phobos777** [comment]
here is something i found from another github doing search.   could be workaround?:

https://gist.github.com/leolin310148/e545438aecba9cc4c9c313ee2c2ed8bb

**Comment by 333miiko** [comment]
Yes this is very weird, docker should not have this kind of issue.

You can try use the official version, try this:

```
apt-get remove docker docker-engine docker.io
apt-get update
apt-get install \
    apt-transport-https \
    ca-certificates \
    curl \
    software-properties-common
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
apt-key fingerprint 0EBFCD88
add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
   $(lsb_release -cs) \
   stable"
apt-get update
apt-get install docker-ce
```

Then check if docker has started:

```
systemctl status docker
```

**Comment by phobos777** [comment]
fail fail fail.  :(    . . . maybe it's a support ticket with Linode.    (curious of that work around works though)


Job for docker.service failed because the control process exited with error code. See "systemctl status docker.service" and "journalctl -xe" for details.
invoke-rc.d: initscript docker, action "start" failed.
● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Sat 2018-08-11 13:05:19 UTC; 19ms ago
     Docs: https://docs.docker.com
  Process: 7165 ExecStart=/usr/bin/dockerd -H fd:// (code=exited, status=1/FAILURE)
 Main PID: 7165 (code=exited, status=1/FAILURE)

Aug 11 13:05:19 localhost systemd[1]: docker.service: Main process exited, code=exited, status=1/FAILURE
Aug 11 13:05:19 localhost systemd[1]: Failed to start Docker Application Container Engine.
Aug 11 13:05:19 localhost systemd[1]: docker.service: Unit entered failed state.
Aug 11 13:05:19 localhost systemd[1]: docker.service: Failed with result 'exit-code'.
dpkg: error processing package docker-ce (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 docker-ce
E: Sub-process /usr/bin/dpkg returned an error code (1)
root@localhost:~# systemctl status docker
● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
   Active: inactive (dead) (Result: exit-code) since Sat 2018-08-11 13:05:21 UTC; 8s ago
     Docs: https://docs.docker.com
  Process: 7209 ExecStart=/usr/bin/dockerd -H fd:// (code=exited, status=1/FAILURE)
 Main PID: 7209 (code=exited, status=1/FAILURE)

Aug 11 13:05:21 localhost systemd[1]: docker.service: Main process exited, code=exited, status=1/FAILURE
Aug 11 13:05:21 localhost systemd[1]: Failed to start Docker Application Container Engine.
Aug 11 13:05:21 localhost systemd[1]: docker.service: Unit entered failed state.
Aug 11 13:05:21 localhost systemd[1]: docker.service: Failed with result 'exit-code'.
Aug 11 13:05:21 localhost systemd[1]: docker.service: Service hold-off time over, scheduling restart.
Aug 11 13:05:21 localhost systemd[1]: Stopped Docker Application Container Engine.
Aug 11 13:05:21 localhost systemd[1]: docker.service: Start request repeated too quickly.
Aug 11 13:05:21 localhost systemd[1]: Failed to start Docker Application Container Engine.
root@localhost:~#

**Comment by 333miiko** [comment]
`systemctl status -l docker`

**Comment by phobos777** [comment]
Welcome to Ubuntu 16.04.5 LTS (GNU/Linux 4.17.14-x86_64-linode113 x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
Last login: Sat Aug 11 11:36:28 2018 from 76.119.196.29
root@localhost:~# systemctl status -l docker
● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: e
   Active: failed (Result: exit-code) since Sat 2018-08-11 11:42:06 UTC; 4h 19mi
     Docs: https://docs.docker.com
  Process: 745 ExecStart=/usr/bin/dockerd -H fd:// $DOCKER_OPTS (code=exited, st
 Main PID: 745 (code=exited, status=1/FAILURE)

Aug 11 11:42:05 localhost systemd[1]: Starting Docker Application Container Engi
Aug 11 11:42:05 localhost dockerd[745]: time="2018-08-11T11:42:05.575373465Z" le
Aug 11 11:42:06 localhost dockerd[745]: time="2018-08-11T11:42:06.598805510Z" le
Aug 11 11:42:06 localhost dockerd[745]: time="2018-08-11T11:42:06.599386294Z" le
Aug 11 11:42:06 localhost dockerd[745]: Error starting daemon: error initializin
Aug 11 11:42:06 localhost systemd[1]: docker.service: Main process exited, code=
Aug 11 11:42:06 localhost systemd[1]: Failed to start Docker Application Contain
Aug 11 11:42:06 localhost systemd[1]: docker.service: Unit entered failed state.
Aug 11 11:42:06 localhost systemd[1]: docker.service: Failed with result 'exit-c
lines 1-16/16 (END)
● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sat 2018-08-11 11:42:06 UTC; 4h 19min ago
     Docs: https://docs.docker.com
  Process: 745 ExecStart=/usr/bin/dockerd -H fd:// $DOCKER_OPTS (code=exited, status=1/FAILURE)
 Main PID: 745 (code=exited, status=1/FAILURE)

Aug 11 11:42:05 localhost systemd[1]: Starting Docker Application Container Engine...
Aug 11 11:42:05 localhost dockerd[745]: time="2018-08-11T11:42:05.575373465Z" level=info msg="libcontainerd: new containerd process, pid: 761"
Aug 11 11:42:06 localhost dockerd[745]: time="2018-08-11T11:42:06.598805510Z" level=error msg="'overlay' not found as a supported filesystem on
Aug 11 11:42:06 localhost dockerd[745]: time="2018-08-11T11:42:06.599386294Z" level=error msg="[graphdriver] prior storage driver overlay2 faile
Aug 11 11:42:06 localhost dockerd[745]: Error starting daemon: error initializing graphdriver: driver not supported
Aug 11 11:42:06 localhost systemd[1]: docker.service: Main process exited, code=exited, status=1/FAILURE
Aug 11 11:42:06 localhost systemd[1]: Failed to start Docker Application Container Engine.
Aug 11 11:42:06 localhost systemd[1]: docker.service: Unit entered failed state.
Aug 11 11:42:06 localhost systemd[1]: docker.service: Failed with result 'exit-code'.
~

**Comment by 333miiko** [comment]
The error seems to be related to a change in kernel version I'm guessing, try this:

```
systemctl stop docker
cp -au /var/lib/docker /var/lib/docker.bk
```

# Edit /etc/docker/daemon.json. If it does not yet exist, create it. Assuming that the file was empty, add the following contents.
```
{
  "storage-driver": "overlay2"
}
```

```
systemctl start docker
```

**Comment by phobos777** [comment]
my servers are out of atlanta GA that are having issues.

@333miiko    and i added the daemon.json.    (ps the cp filled the the hard disk so i skipped the docker.bk).

here are results back:
-- The start-up result is done.
Aug 12 00:46:56 localhost systemd[1]: Starting Docker Application Container Engine...
-- Subject: Unit docker.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit docker.service has begun starting up.
Aug 12 00:46:57 localhost dockerd[1831]: time="2018-08-12T00:46:57.195042530Z" level=info msg="libcontainerd: new containerd process, pid: 1835"
Aug 12 00:46:58 localhost dockerd[1831]: time="2018-08-12T00:46:58.219445187Z" level=error msg="'overlay' not found as a supported filesystem on th
Aug 12 00:46:58 localhost dockerd[1831]: Error starting daemon: error initializing graphdriver: driver not supported
Aug 12 00:46:58 localhost systemd[1]: docker.service: Main process exited, code=exited, status=1/FAILURE
Aug 12 00:46:58 localhost systemd[1]: Failed to start Docker Application Container Engine.
-- Subject: Unit docker.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit docker.service has failed.
--
-- The result is failed.
Aug 12 00:46:58 localhost systemd[1]: docker.service: Unit entered failed state.
Aug 12 00:46:58 localhost systemd[1]: docker.service: Failed with result 'exit-code'.

**Comment by 333miiko** [comment]
I believe the underlying issue may be because Linode is running their own kernel. Could you check here https://www.linode.com/docs/tools-reference/custom-kernels-distros/run-a-distribution-supplied-kernel-with-kvm/ and see what kernel you have selected?

Most likely the case is they've updated the kernel which no longer supports the overlay driver.

**Comment by 333miiko** [comment]
Picking full virtualisation will should fix the kernel issues permanently.

**Comment by phobos777** [comment]
sorry to report that the full virtualzation doesn't work.  :'(   . . . what i did was: 1) new image, 2) install.sh, 3)  it got down to docker setup scripts, and then came back to "docker working errors as we've seen.

workaround is still to use the "linode107".   p.s. other versions in that are newer are not working either.  i.e. 113,112, 108 do not work.

**Comment by 333miiko** [comment]
The numbers at the start are more important, what are the kernel versions which are working

**Comment by phobos777** [comment]
this was the only kernel i got running by linode.  i tried about 6-8 different ones.  (but not them all as there was like 40+ versions there:   4.15.18-x86_64-linode107

**Comment by phobos777** [comment]
unbuntu 16.04

**Comment by ben-xx** [comment]
Thanks @333miiko for the [Linode link to kernels](https://www.linode.com/docs/tools-reference/custom-kernels-distros/run-a-distribution-supplied-kernel-with-kvm/).  According to the article we can boot our Linode using the distro's default kernel by choosing GRUB2 from the Linode Dashboard > Edit > Configuration Profile > Boot Settings > Kernel dropdown list.  (Just make sure Linode is shut down before doing this.)  This doesn't erase the current disk contents, it just boots our install against the infrastructure of the selected kernel.

GRUB2 allows us to use the latest official distro kernel for Ubuntu 16.04 LTS (to the best of my understanding)

<img width="778" alt="grub2_kernel_image_linode" src="https://user-images.githubusercontent.com/5800/44062489-6d43019a-9f11-11e8-8586-cd4afab337c7.png">

After switching from Latest 64-bit kernel to GRUB2, the install.sh script finished without a hitch.

Now just waiting for blocks to to update...

**Comment by phobos777** [comment]
GRUB2 is working well!  @333miiko   is that okay to keep using?  and will be the latest?  any conflicts that you see with using GRUB2?   (love the name.  LOL)

**Comment by 333miiko** [comment]
This is a linode problem, they have pushed a fix.

https://www.linode.com/community/questions/17114/docker-wont-start-using-the-latest-linode-kernel

If you want to avoid this issue happening again you may want to use the distribution provided kernel https://linode.com/docs/tools-reference/custom-kernels-distros/run-a-distribution-supplied-kernel/
