### ISSUE TITLE
Is 'super' being properly set during setup?

### ISSUE THREAD

**Issue by KenJusticeJr** [WhenLamboMoon/docker-zen-node#102]
During Super Node setup, the node is getting registered to the SecureNodes tracker site instead of the SuperNodes site. The values in config.json are properly set to super. Is there perhaps some step in the docker install process that is being missed? During a manual install, setup.js gives a prompt to enter secure or super. Is that perhaps not being relayed in the docker install? I've tried unsuccessfully to find that point in this repository.

**Comment by jurgis** [comment]
Supernodes use different servers:
* xns1.eu, xns2.eu, xns3.eu, xns4.eu
* xns1.na, xns2.na, xns3.na, xns4.na

Try updating config.json file with those servers.
The install script does not do that yet.

**Comment by KenJusticeJr** [comment]
Thank you. I was just arriving at that conclusion as well.

It must be pulling the servers from https://securenodes.zensystem.io/api/srvlist instead of https://supernodes.zensystem.io/api/srvlist

**Comment by jurgis** [comment]
The servers are hardcoded in the install script.
But that is a good idea to pull the servers from the api.

**Comment by jurgis** [comment]
You can do that or just change the config file and restart the tracker service.
You can try with the existing address first and if that does not work try a new address.

**Comment by KenJusticeJr** [comment]
Changing the config file and restarting did not work.

I was, however, able to manually edit the install script with the xns servers, and rerun the installation with the same stake address, and it seems to have worked.

Thanks for your help!

**Comment by 333miiko** [comment]
Fix is here. Please try re-run the installer https://github.com/WhenLamboMoon/docker-zen-node/commit/1048f7b9e6500d5d3c6a00b27520ad48de9bba9b
