### ISSUE TITLE
low disk space on vps

### ISSUE THREAD

**Issue by phobos777** [WhenLamboMoon/docker-zen-node#105]
I'm getting Low disk space on OHV servers.  (mainly because they only have 20gb disks).  however what else in the image can we trim down?  (or backups to minimize) to keep servers from crashing?  thanks!  @333miiko 

here is a df:

root@vps496920:~# df
Filesystem     1K-blocks     Used Available Use% Mounted on
udev             1964756        0   1964756   0% /dev
tmpfs             394816    40284    354532  11% /run
/dev/sda1       20263528 20246976       168 100% /
tmpfs            1974060      140   1973920   1% /dev/shm
tmpfs               5120        0      5120   0% /run/lock
tmpfs            1974060        0   1974060   0% /sys/fs/cgroup
tmpfs             394816        0    394816   0% /run/user/0
none            20263528 20246976       168 100% /var/lib/docker/aufs/mnt/6412c7a14e076d5e125e04b6ed7594a742c530dcab0ffcedcad99b7f478fc65e
shm                65536        0     65536   0% /var/lib/docker/containers/ce9e465e0394e274904719c20029470ea1df78bf5ba19e51059ce161773dc158/shm
none            20263528 20246976       168 100% /var/lib/docker/aufs/mnt/3dba7be8ae0e02fa31a006d9efb521dca176a4bd6879c4856801fe7aa3023dfc
shm                65536        0     65536   0% /var/lib/docker/containers/d507176b5500d44829526297f7468861afbb9aba3065d16813d803334018a44c/shm

**Comment by phobos777** [comment]
and i do run this when server fills up.  but it's doesn't buy enough time/space:

systemctl stop zen-node && systemctl stop zen-secnodetracker && /usr/bin/docker rmi $(/usr/bin/docker images -q -f dangling=true) && apt-get update && apt-get -y upgrade

**Comment by phobos777** [comment]
and after issuing that.  here is the output.  so feels like other docker.bk?


root@vps496920:~# df
Filesystem     1K-blocks     Used Available Use% Mounted on
udev             1964756        0   1964756   0% /dev
tmpfs             394816    40216    354600  11% /run
/dev/sda1       20263528 18576884   1670260  92% /
tmpfs            1974060       48   1974012   1% /dev/shm
tmpfs               5120        0      5120   0% /run/lock
tmpfs            1974060        0   1974060   0% /sys/fs/cgroup
tmpfs             394816        0    394816   0% /run/user/0
none            20263528 18576884   1670260  92% /var/lib/docker/aufs/mnt/6412c7a14e076d5e125e04b6ed7594a742c530dcab0ffcedcad99b7f478fc65e
shm                65536        0     65536   0% /var/lib/docker/containers/ce9e465e0394e274904719c20029470ea1df78bf5ba19e51059ce161773dc158/shm
root@vps496920:~#

**Comment by phobos777** [comment]
i ran this command, and it seems to work.  not sure if this is a good idea or not.  :) 

rm -r /var/lib/docker/aufs/mnt/*

**Comment by darkoopa** [comment]
I had the problem few month ago and 333miiko told me to use these commands:

```
systemctl stop zen-node
systemctl stop zen-secnodetracker
systemctl stop acme-sh
```

```
docker rm $(docker ps -a -q)
docker rmi $(docker images -q)
```

```
systemctl start zen-node
systemctl start zen-secnodetracker
systemctl start acme-sh
```

**Comment by 333miiko** [comment]
The newer versions of docker will also allow you to use:

```
docker system prune -a
```

This can clean up all your old images. In this case above, Docker was only using 1GB and the rest was the blockchain and OS. 

@darkoopa if you use the latest installer it'll replace acme-sh with certbot which will help with auto rebots and the updater included also cleans up old Docker images.
