### ISSUE TITLE
Permissions, (small thing)

### ISSUE THREAD

**Issue by phobos777** [WhenLamboMoon/docker-zen-node#106]
next time you update the image can you add this in there please?  (i know you said it's in there but maybe reissue one at the beginning and one at the end?)   

chmod -R 755 /etc/letsencrypt/ && chmod -R 777 /mnt/zen/secnode/

reason why, is that on existing secure nodes.  while upgrading,   and very infrequently,  sometimes the challenges are not completing still.   i can't find a reason why, other than perhaps the previous image excluses permissions or something.   (so tracker 2.0 to 3.1 upgrade)

this problem happens once every 10 upgrades or so,  so small issue.  thanks!

**Comment by 333miiko** [comment]
This is already happening within the installer and image.
