### ISSUE TITLE
Improve docs and troubleshooting guide

### ISSUE THREAD

**Issue by 333miiko** [WhenLamboMoon/docker-zen-node#11]
Tracking issue for docs improvement and troubleshooting guides

**Comment by greerso** [comment]
From a comment on https://blockoperations.com/how-to-build-and-operate-a-zencash-secure-node/

>reduce the amount of ZEN needed on nodes that go directly to main, the 1 ZEN suggestion was based on multiple challenges/day, now with only one per day 5 * 0.03 payments will last ~3 years which is probably more than enough for most people.>
