### ISSUE TITLE
error when running the script

### ISSUE THREAD

**Issue by phobos777** [WhenLamboMoon/docker-zen-node#12]
here is the error i get, when running the script:

## Enabling fail2ban services...

Synchronizing state of fail2ban.service with SysV init with /lib/systemd/systemd-sysv-install...
Executing /lib/systemd/systemd-sysv-install enable fail2ban

## Waiting for node to fetch params ...

**Error response from daemon: No such container: zen-node**
^^^ and this happens over and over

**Comment by mattaero** [comment]
I am running into the same error.  Thanks for the script!

**Comment by 333miiko** [comment]
What base operating system did you use?

Can you run the following and show me the output:

```
systemctl stop zen-node
docker run --rm \
                              -p 9033:9033 \
                              -p 18231:18231 \
                              -v /mnt/zen:/mnt/zen \
                              --name zend zend
```

**Comment by mattaero** [comment]
Im using Putty in Windows 10 with a Vultr 16.04 Ubuntu server.  
Here is what I get:

root@vultr:~# systemctl stop zen-node
root@vultr:~# docker run --rm  -p 9033:9033 -p 18231:18231 -v /mnt/zen:/mnt/zen --name zend zend
Unable to find image 'zend:latest' locally
docker: Error response from daemon: repository zend not found: does not exist or no pull access.
See 'docker run --help'.

**Comment by mattaero** [comment]
[zennode log script.txt](https://github.com/WhenLamboMoon/docker-zen-node/files/1523381/zennode.log.script.txt)

This is what happens after I run the second command with my address, email and domain

**Comment by 333miiko** [comment]
Sorry the command should be:

```
/usr/bin/docker run --rm --net=host -v /mnt/zen:/mnt/zen --name zen-secnodetracker whenlambomoon/secnodetracker:latest
```

**Comment by mattaero** [comment]
root@vultr:~# /usr/bin/docker run --rm --net=host -v /mnt/zen:/mnt/zen --name zen-secnodetracker whenlambomoon/secnodetracker:latest
/usr/bin/docker: Error response from daemon: Conflict. The container name "/zen-secnodetracker" is already in use by container d9d328350f5f281da7af9c2de289795a19d546d646a1151a3298bb3e612a8931. You have to remove (or rename) that container to be able to reuse that name..
See '/usr/bin/docker run --help'.

**Comment by 333miiko** [comment]
Ah wait sorry. 

```
systemctl stop zen-node
/usr/bin/docker run --rm --net=host -p 9033:9033 -p 18231:18231 -v /mnt/zen:/mnt/zen --name zen-node whenlambomoon/zend:latest
```

**Comment by mattaero** [comment]
root@vultr:~# systemctl stop zen-node
root@vultr:~# /usr/bin/docker run --rm --net=host -p 9033:9033 -p 18231:18231 -v /mnt/zen:/mnt/zen --name zen-node whenlambomoon/zend:latest
Starting with UID/GID : 9001/9001
No config found. Exiting.
root@vultr:~#

**Comment by 333miiko** [comment]
This line from your logs looks like the most likely culprit, 

`./install.sh: 100: ./install.sh: cannot create /mnt/zen/config/zen.conf: Directory nonexistent`

Can you run

```
ls /mnt/
ls /mnt/zen/
```

**Comment by 333miiko** [comment]
Are you running the install.sh as root?

**Comment by mattaero** [comment]
Yes... Should i create a user?

**Comment by mattaero** [comment]
root@vultr:~# ls /mnt/
zen
root@vultr:~# ls /mnt/zen/
certs  {config,data,zcash-params,certs}  secnode
root@vultr:~#

**Comment by 333miiko** [comment]
No it needs to run as root.

Ok we found your issue! The folders weren't created properly did you use:

```
./install.sh <stakeaddr> <email> <fqdn> <region>
```

or 
```
sh ./install.sh <stakeaddr> <email> <fqdn> <region>
```

Try run it again with (remove sh):

```
./install.sh <stakeaddr> <email> <fqdn> <region>
```

**Comment by mattaero** [comment]
It was with sh originally, not sure how I did that... instead now I get "-bash: ./install.sh: permission denied

LOL.  dammit.

This is a great script, because the whole process for a non-technical person is daunting.  Also, for the wallet with 43 zen, can I send the 1 zen to the shield address from that address?

**Comment by 333miiko** [comment]
Ok can you try

```
chmod +x install.sh
./install.sh <stakeaddr> <email> <fqdn> <region>
```

Yes you can, but you'll want to send it in increments of 0.25 per transaction. So send 0.25 zen 4 times to the shield address

**Comment by mattaero** [comment]
Now I am getting this error, in the same spot as before, but its not the same issue server issues?:


## Enabling fail2ban services...

Synchronizing state of fail2ban.service with SysV init with /lib/systemd/systemd-sysv-install...
Executing /lib/systemd/systemd-sysv-install enable fail2ban

## Waiting for node to fetch params ...

error: couldn't connect to server: unknown (code -1)
(make sure server is running and you are connecting to the correct RPC port)
..
error: couldn't connect to server: unknown (code -1)
(make sure server is running and you are connecting to the correct RPC port)
..

**Comment by 333miiko** [comment]
You'll first need to stop the debug container I asked you to run before:

```
docker stop zen-node
docker rm zen-node
systemctl stop zen-node
```

Are you on zencash slack do you want to PM me there?

**Comment by mattaero** [comment]
I am not on the slack, and I can't figure out how to get an invite.  I can PM you once I am there.

I need to stop the debug container before I do what? transfer the coins?  Also, how do I start everything again? lol  (Sucks not being that technical)

**Comment by 333miiko** [comment]
Ok I just suggested joining slack since I could help you faster.

If you haven't transferred any coins and you aren't technical, you could try "reinstall your VPS" with Vultr and run the installer again this time using:

./install.sh instead of sh ./install.sh

Perhaps start fresh will be the easiest for you.

**Comment by mattaero** [comment]
I found the telegram link if you are on there.

**Comment by 333miiko** [comment]
Sorry I'm not

**Comment by joshma91** [comment]
Thanks for making this miiko. I'm getting this error when running the install script:
```
[Sat Dec  2 02:28:55 UTC 2017] Getting new-authz for domain='li602-43.members.linode.com'
[Sat Dec  2 02:28:55 UTC 2017] It seems the CA server is busy now, let's wait and retry.
[Sat Dec  2 02:29:01 UTC 2017] It seems the CA server is busy now, let's wait and retry.
[Sat Dec  2 02:29:06 UTC 2017] It seems the CA server is busy now, let's wait and retry.
[Sat Dec  2 02:29:12 UTC 2017] The new-authz request is ok.
[Sat Dec  2 02:29:12 UTC 2017] **new-authz error: {"type":"urn:acme:error:rejectedIdentifier","detail":"Error creating new authz :: Policy forbids issuing for name","status": 400}**
[Sat Dec  2 02:29:12 UTC 2017] Please add '--debug' or '--log' to check more details.
[Sat Dec  2 02:29:12 UTC 2017] See: https://github.com/Neilpang/acme.sh/wiki/How-to-debug-acme.sh

## Error provisioning certificate for domain.. exiting
```
Do you have any suggestions on how to fix this?

**Comment by 333miiko** [comment]
@joshma91 I believe you need to use your own domain name, you can't use li602-43.members.linode.com

**Comment by joshma91** [comment]
Thank you!!

**Comment by mattaero** [comment]
I sent you a zen, this script made my life many times easier.  If you could provide a way to send the 4 small transactions easier, that would solve the last major hurdle.

Also, you may want to add the VPNs should ensure they have ipv6 enabled.  On the servers I had it disabled, I constantly couldn't find enough peers for the node, but the serves I had in enabled had no issues.  (I am a noob, so maybe that is obvious, but it would have been good to know)

**Comment by 333miiko** [comment]
Thanks @mattaero 

There'll be a patch to zen coming soon that will fix the issue with peers disconnecting. There's a bug that the zen team are working on fixing now. When it's released I will push the update and you'll just need to run the following command to update your node to the latest version.

```
systemctl restart zen-node
```

**Comment by 333miiko** [comment]
Also the arizen 2.0 wallet will make sending the 4 transactions easier, that's also very close too.

**Comment by mattaero** [comment]
Nice.  I appreciate the update :)

**Comment by 333miiko** [comment]
Feel free to re-open if you have any other issues.
