### ISSUE TITLE
Why copy zcash-params in the node tracker entrypoint?

### ISSUE THREAD

**Issue by andyfo** [WhenLamboMoon/docker-zen-node#122]
Hello – 

I couldn't find out why this was important, so could you please explain to me why you copy zcash-params in the node tracker entrypoint?

`cp -r /mnt/zen/zcash-params /mnt/zcash-params`

https://github.com/WhenLamboMoon/docker-zen-node/blob/master/secnodetracker/entrypoint.sh#L13

Thank you!

**Comment by 333miiko** [comment]
This was due to a permissions error last time when doing a symlink
