### ISSUE TITLE
Docker keeps filling drive up

### ISSUE THREAD

**Issue by slayorktc** [WhenLamboMoon/docker-zen-node#123]
I keep running into disk space issues. The current docker dir is taking over 4gigs. /var/lib/docker

Not sure if we can shrink this down at all.

**Comment by 333miiko** [comment]
The actual images are only

200mb and 100mb
https://hub.docker.com/r/whenlambomoon/secnodetracker/tags
https://hub.docker.com/r/whenlambomoon/zend/tags

The issue is old images are not getting pruned, you'll need to clear them up manually after every upgrade.
