### ISSUE TITLE
update documentation

### ISSUE THREAD

**Issue by sebavasile** [WhenLamboMoon/docker-zen-node#124]
The command for reindex misses the letsencrypt volume pass to docker. It should be:
docker run --rm --net=host -p 9033:9033 -p 18231:18231 -v /mnt/zen:/mnt/zen -v /etc/letsencrypt/:/etc/letsencrypt --name zen-node whenlambomoon/zend:latest zend -reindex

**Comment by 333miiko** [comment]
Thanks for catching this, do you mind creating a PR to fix this. Thanks
