### ISSUE TITLE
Hard fork build failing.

### ISSUE THREAD

**Issue by slayorktc** [WhenLamboMoon/docker-zen-node#125]
Tag	Created	Last Updated
Failed
latest	2 days ago	2 days ago
Failed
latest	5 days ago	5 days ago
Failed
latest	5 days ago	5 days ago
Failed
latest	5 days ago	5 days ago

The latest docker builds are failing. It is not pulling down the latest zen which is required next week.

**Comment by slayorktc** [comment]
I would go and try to figure out how to solve this but not sure how to see why the failure is occurring.

**Comment by slayorktc** [comment]
Yeah I see something was updated in the docker image 12 days ago but can't see exactly what the change was. I also can't seem to figure out what the build failed error is.

**Comment by slayorktc** [comment]
gpg: directory `/root/.gnupg' created
gpg: new configuration file `/root/.gnupg/gpg.conf' created
gpg: WARNING: options in `/root/.gnupg/gpg.conf' are not yet active during this run
gpg: keyring `/root/.gnupg/secring.gpg' created
gpg: keyring `/root/.gnupg/pubring.gpg' created
gpg: requesting key 4991B669 from hkp server ha.pool.sks-keyservers.net
gpgkeys: key 219F55740BBF7A1CE368BA45FB7053CE4991B669 can't be retrieved
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0
gpg: keyserver communications error: keyserver helper general error
gpg: keyserver communications error: unknown pubkey algorithm
gpg: keyserver receive failed: unknown pubkey algorithm


I think this is what is breaking the build.

**Comment by slayorktc** [comment]
I copied the Dockerfile to my personal machine and got the build to work and then got the build to crash about validating pgp keys. I am going to try and pull from yours again and see if the latest zen comes down.

**Comment by 333miiko** [comment]
Unfortunately I haven't really had much time to maintain this as much as I would have liked

The error is some how related to the gpg key of the zend package. I'll try push an update.

**Comment by slayorktc** [comment]
Your image is def the problem. building it with the exact same dockerfile on my machine worked. I did get it to fail about gpg keys but deleting all the images:
 docker rmi $(docker images -q) --force

Then building again got the keys to validate and build successfully. 

please try and get your image working else ill have to go modify all my nodes to use a fork. Rather not do that.

**Comment by 333miiko** [comment]
```
Need to get 27.3 MB of archives.
After this operation, 140 MB of additional disk space will be used.
Err:1 https://zencashofficial.github.io/repo xenial/main amd64 zen amd64 2.0.16
503 backend read error
E: Failed to fetch https://zencashofficial.github.io/repo/pool/main/z/zen/zen_2.0.16_amd64.deb 503 backend read error
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
Removing intermediate container e949ce76d2db
The command '/bin/sh -c apt-get update && DEBIAN_FRONTEND=noninteractive apt-get -y --no-install-recommends install ca-certificates curl wget apt-transport-https lsb-release libgomp1 jq && echo 'deb https://zencashofficial.github.io/repo/ '$(lsb_release -cs)' main' | tee --append /etc/apt/sources.list.d/zen.list && gpg --keyserver ha.pool.sks-keyservers.net --recv 219F55740BBF7A1CE368BA45FB7053CE4991B669 && gpg --export 219F55740BBF7A1CE368BA45FB7053CE4991B669 | apt-key add - && apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install zen && latestBaseurl="$(curl -s https://api.github.com/repos/tianon/gosu/releases | grep browser_download_url | head -n 1 | cut -d '"' -f 4 | sed 's:/[^/]*$::')" && dpkgArch="$(dpkg --print-architecture | awk -F- '{ print $NF }')" && curl -o /usr/local/bin/gosu -SL "$latestBaseurl/gosu-$dpkgArch" && curl -o /usr/local/bin/gosu.asc -SL "$latestBaseurl/gosu-$dpkgArch.asc" && export GNUPGHOME="$(mktemp -d)" && gpg --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4 && gpg --batch --verify /usr/local/bin/gosu.asc /usr/local/bin/gosu && rm -r "$GNUPGHOME" /usr/local/bin/gosu.asc && chmod +x /usr/local/bin/gosu && gosu nobody true && apt-get clean && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100
```

This is the last build error fail

**Comment by slayorktc** [comment]
So strange since copying the Dockerfile to my machine and building locally seems to work. Not sure what is happening on docker hub or what that build process is but something seems to be messed up. If you can't seem to figure it out, I can build them myself and deploy before the hard fork.

**Comment by 333miiko** [comment]
Looks like it passed this time. Must've been a problem with dockerhub or interim problems with the zencash repository

**Comment by slayorktc** [comment]
https://hub.docker.com/r/whenlambomoon/secnodetracker/builds

Failed build for the last 3 months. 

0.4.0 node tracker software has been released but build it not pulling it down.

**Comment by slayorktc** [comment]
We have a hard fork due date. It is march 1st. Can you check your docker hub builds and see what is causing the failure?

**Comment by jurgis** [comment]
This is a different issue similar to the one mentioned here:
https://github.com/nodejs/docker-node/issues/922
I could build the image locally when added --no-tty to gpg

**Comment by 333miiko** [comment]
:crossed_fingers:
