### ISSUE TITLE
Are we allset for 2.0.16?

### ISSUE THREAD

**Issue by phobos777** [WhenLamboMoon/docker-zen-node#128]
hi Miikko! hope all is well.  are we all set for the new version of zend in the docker image?  and i guess i can just reboot the vps' as needed?  (at this point i havn't seen the node pick up 1650 yet,  (as they are still at 1550, which is why i'm asking).   let me know if i can help test in someway.   thanks!

**Comment by Przemek** [comment]
Hi
reboot was all I needed for upgrade.
Just make sure to check if everything is fine once your node starts, especially check as recommended in point 6. of the upgrade instruction:
https://horizenofficial.atlassian.net/wiki/spaces/ZEN/pages/136872130/Upgrade+zend+daemon+using+apt

**Comment by 333miiko** [comment]
Yep, the image should be up to date.
