### ISSUE TITLE
zend 2.0.17

### ISSUE THREAD

**Issue by jurgis** [WhenLamboMoon/docker-zen-node#130]
Could you please trigger docker build so we can use whenlambomoon/zend
docker repo to upgrade to 2.0.17.
There are only a few days left.

**Comment by 333miiko** [comment]
https://cloud.docker.com/u/whenlambomoon/repository/registry-1.docker.io/whenlambomoon/zend/builds/60411491-35b0-41bc-a177-3cd6939da021

**Comment by jurgis** [comment]
That link did not work for me, but I can see the new build.
https://hub.docker.com/r/whenlambomoon/zend/builds
Will check it out shortly. Thank you!

**Comment by jurgis** [comment]
All good, thank you!
