### ISSUE TITLE
new zend coming

### ISSUE THREAD

**Issue by phobos777** [WhenLamboMoon/docker-zen-node#132]
Hi,  Mikka,  a new zend is coming and the image hasn't updated to the new code.  can you check to make sure we'll be all set for the update please?  thank you!!

**Comment by phobos777** [comment]
Oh oh.   Miikka, are you around to update the Docker Image please?  we have a due date in less then 5 days. please help.   anyone else able to update docker image??

**Comment by 333miiko** [comment]
Sorry for the late reply.

 It should update automatically, if not I will check

**Comment by phobos777** [comment]
thanks! your back.   it's not updating automatically. . . not 100% why.  . .  thank you as your on the case.  :)

**Comment by phobos777** [comment]
as a side note, docker images are getting huge and alot of images are filling up to 100% diskspace.  for me i've issued "df -h && docker system prune"  which cleans up 1-3gb of disk space, but the only way to reclaim of all of the space is to flatten and reinstall as a new image.

. . . therefore consider not going forward with docker if it's more then needed.  just my .02 .   thank you for everything btw.

**Comment by phobos777** [comment]
example:

**Comment by 333miiko** [comment]
It's updated now

**Comment by XeZZoR** [comment]
Works can be closed ;)
