### ISSUE TITLE
ZEN 2.0.18 Tech Note - Node unable to pass challenge

### ISSUE THREAD

**Issue by kareem613** [WhenLamboMoon/docker-zen-node#134]
From the announcement in #node_announcements in the horizen discord. 

> Background
Some nodes are no longer able to pass a challenge after upgrading to 2.0.18.  The apparent cause is an update in one of the dependent libraries that provides a random generator to zen. The library was enhanced to provide entropy based on the operating system.  Some virtual systems are unable to provide a proper level of entropy due to sharing between multiple environments.

I believe this is impacting docker support as well. Is there something that can be done in the image to handle this?

> To determine if a VPS uses OpenVZ run the following at the command prompt: systemd-detect-virt

I tried that at the shell in the container and it says "command not found".

**Comment by 333miiko** [comment]
This would be due to your underlying VPS rather than docker.
