### ISSUE TITLE
Update to Zen 2.0.19

### ISSUE THREAD

**Issue by krisivanov** [WhenLamboMoon/docker-zen-node#139]
Please update script for Zen 2.0.19
I tied reboot and re-install and it is still showing Zen 2.0.18

Thanks

P.S.: Zen v2.0.18 will stop working at block height 610000, estimated to occur October 26th at about 12:00 UTC.

**Comment by cgaspart** [comment]
It's not script just the docker image need to be updated... I wait for it too

**Comment by 333miiko** [comment]
https://cloud.docker.com/u/whenlambomoon/repository/registry-1.docker.io/whenlambomoon/zend/builds/addddc28-7cd9-453e-8cdc-fea387cf0fe9

**Comment by krisivanov** [comment]
Any instructions would be helpful.
Thanks

**Comment by cgaspart** [comment]
@krisivanov Just restart your server and exec: `docker exec zen-node gosu user zen-cli getinfo` after reboot `version` should be `2001950`

**Comment by krisivanov** [comment]
@cgaspart Thanks, that updated to 2001950 successfully
