### ISSUE TITLE
update to latest version

### ISSUE THREAD

**Issue by cryptouse** [WhenLamboMoon/docker-zen-node#14]
hi,
how to update to latest version after using your script ?
as version of zend you are using have problems with keeping connections.

**Comment by 333miiko** [comment]
The container installs the latest version of zend available from https://github.com/ZencashOfficial/repo

When a new version is available you can run `systemctl restart zen-node` to get the latest version.

**Comment by cryptouse** [comment]
I see. 
Is there a chance to "swap" the one that we have to one we compiled by our own ?
as I see official repo is not so fast with updates

**Comment by 333miiko** [comment]
Yeah, you'll need to build your own docker image and instead of using the official repository you can compile zen from source. 

This is the Dockerfile I use for the zen container https://github.com/WhenLamboMoon/docker-zen-node/blob/master/zend/Dockerfile#L10

**Comment by 333miiko** [comment]
If you need help creating your own docker image feel free to let me know. Otherwise the new version of zen will be updated soon.
