### ISSUE TITLE
Mandatory Software Upgrade: ZEN 2.0.20

### ISSUE THREAD

**Issue by DocBrown101** [WhenLamboMoon/docker-zen-node#142]
ZEN 2.0.20 replaces the current version, ZEN 2.0.19-1, which is set to deprecate (no longer run). The focus of this version is general maintenance, and it includes the fixes and features listed below.

Please update your ZEN software before the 25th of February. The new 2.0.20 version is available now at https://github.com/ZencashOfficial/zen/releases/tag/v2.0.20 or through the APT repository.

**Can we hope that the update will be implemented here?**

**Comment by 333miiko** [comment]
https://hub.docker.com/repository/registry-1.docker.io/whenlambomoon/zend/builds/0df1db00-e7ec-41ba-a478-0edfe1d0065c
