### ISSUE TITLE
Ubuntu

### ISSUE THREAD

**Issue by avrossi** [WhenLamboMoon/docker-zen-node#15]
I'm trying to figure out how to run this script. Do I need to install Ubuntu to my desktop or can I do it all through digital ocean and puTTY?

**Comment by 333miiko** [comment]
You will need to do it all on a VPS like digitalocean (through putty if you use windows).

- Deploy a VPS on digitalocean/ovh etc.
- Get a domain name, and create a DNS record eg. node1.example.com -> your digitalocean IP address
- SSH into your VPS (with putty)
- Run the commands from this script and you're good to go :) 

Feel free to let me know if you have any other questions

**Comment by avrossi** [comment]
Thanks a lot.  I'll give it a shot!
