### ISSUE TITLE
Error response from daemon:  No such container: acme-ch

### ISSUE THREAD

**Issue by avrossi** [WhenLamboMoon/docker-zen-node#16]
Im getting this error:   Error response from daemon:  No such container: acme-ch
Any ideas?
Thanks

**Comment by 333miiko** [comment]
When do you get this error? If it's part of the install script and it continues you can ignore this error message. Otherwise please provide me the full output to help you debug

**Comment by avrossi** [comment]
Thanks for your help... This is what I am getting when I run the install script:


## Installing acme container service...

Created symlink from /etc/systemd/system/multi-user.target.wants/acme-sh.service                                                                                                                      to /etc/systemd/system/acme-sh.service.

## Waiting for acme-sh to come up...

Error response from daemon: No such container: acme-sh
..
Main_Domain     KeyLength       SAN_Domains     Created Renew

## Issusing cert for binkernode.com...

[Tue Dec  5 23:51:51 UTC 2017] Standalone mode.
[Tue Dec  5 23:51:51 UTC 2017] Registering account
[Tue Dec  5 23:51:51 UTC 2017] Registered
[Tue Dec  5 23:51:52 UTC 2017] Update account tos info success.
[Tue Dec  5 23:51:52 UTC 2017] ACCOUNT_THUMBPRINT='2RvUWN82z7f1WUM6PFN_ETCHmWWRB                                                                                                                     miPH7s-wPPq1Tc'
[Tue Dec  5 23:51:52 UTC 2017] Creating domain key
[Tue Dec  5 23:51:52 UTC 2017] The domain key is here: /acme.sh/binkernode.com/b                                                                                                                     inkernode.com.key
[Tue Dec  5 23:51:52 UTC 2017] Single domain='binkernode.com'
[Tue Dec  5 23:51:52 UTC 2017] Getting domain auth token for each domain
[Tue Dec  5 23:51:52 UTC 2017] Getting webroot for domain='binkernode.com'
[Tue Dec  5 23:51:52 UTC 2017] Getting new-authz for domain='binkernode.com'
[Tue Dec  5 23:51:53 UTC 2017] The new-authz request is ok.
[Tue Dec  5 23:51:53 UTC 2017] Verifying:binkernode.com
[Tue Dec  5 23:51:53 UTC 2017] Standalone mode server
[Tue Dec  5 23:51:57 UTC 2017] binkernode.com:Verify error:Fetching http://www.b                                                                                                                     inkernode.com/.well-known/acme-challenge/7N1Bs_tazS4sWkDINjFcj9mbAFzCH33UxG6P4Hr                                                                                                                     cOwA: Error getting validation data
[Tue Dec  5 23:51:57 UTC 2017] Please add '--debug' or '--log' to check more det                                                                                                                     ails.
[Tue Dec  5 23:51:57 UTC 2017] See: https://github.com/Neilpang/acme.sh/wiki/How                                                                                                                     -to-debug-acme.sh

## Error provisioning certificate for domain.. exiting

**Comment by avrossi** [comment]
OK sorry I didn't have my Domain pointed at the IP.  It worked now I think!

**Comment by 333miiko** [comment]
Glad you got the issue resolved.

**Comment by avrossi** [comment]
Does this look ok?  I have not sent my 1 Zen over yet but just wondering if this looks good?

root@localhost:~# docker logs zen-secnodetracker
Secure node config found OK - linking...
CPU Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz  cores=1  speed=2499
Tracker app version: 0.1.0
MemTotal: 2.00GB  MemFree: 0.02GB  MemAvailable: 1.71GB  SwapTotal: 4.35GB  SwapFree: 4.33GB
root@localhost:~#

**Comment by 333miiko** [comment]
Yes, that's fine you can look at the example output in the README. The secnodetracker will now continue to restart until you send the 1 ZEN to the shield address

**Comment by avrossi** [comment]
Ok great!  Sorry to keep bugging you. Thank you for your help.

**Comment by 333miiko** [comment]
No worries

**Comment by n8thegrrr8** [comment]
Hi! thanks for doing this; I think I have the same issue with the acme-sh error. I think I have the domain forwarding to my IP, but i'm not sure if I'm using the right port. Is there a specific port I should point it at?

**Comment by 333miiko** [comment]
Do you get this error?

`Error response from daemon: No such container: acme-sh`

This is not actually an error, if it continues to execute. What error do you get?

When you ping yourdomain it should return the IP address, there is no such thing as a specific port for an A address.

If you're using a VPS provider that has their own firewall you need to open the following TCP ports:

22 (ssh)
80 (http)
443 (https)
9033 (zend)

**Comment by n8thegrrr8** [comment]
Thanks a lot, figured out it was not an A address but a redirect. Seems to
be all good now! Thank you thank you!
