### ISSUE TITLE
SSL patch

### ISSUE THREAD

**Issue by mattaero** [WhenLamboMoon/docker-zen-node#17]
I have been having the same connection and oeers issues as several others, and it appears to be an SSL issue.  Is that what you were referring to when you indicated they will be patching soon?

It was this issue: https://github.com/ZencashOfficial/zen/pull/94

Thanks!

**Comment by 333miiko** [comment]
Yes, once they release the new version to the apt repository I'll update the repository and it will resolve your connection issues.

**Comment by mattaero** [comment]
Great.  Thank you!

**Comment by 333miiko** [comment]
The new version that fixes this issue was just released https://github.com/ZencashOfficial/zen/releases

I just finished building a new version of the zend container You can now restart your zen service to get the latest version with the SSL patch

```
systemctl restart zen-node
```

**Comment by mattaero** [comment]
O.o0xproject and to l

On Dec 30, 2017 7:44 AM, "Matthew Derby" <derbymm@gmail.com> wrote:

No, I think it's a good idea.   If you could afford a 15 year mortgage with
a lower rate,  id suggest that,  but I think the purchase is smart.

As for the wealth thing... you hit the nail on the head when you said that
having money gives you options.  I don't care about wealth for the stuff
(well mostly... :))  but being able to do what I want,  when I want,  and
how I want to is important to me.   Time is the most valuable thing I have.
