### ISSUE TITLE
How do I change my staking adress?

### ISSUE THREAD

**Issue by avrossi** [WhenLamboMoon/docker-zen-node#18]
Just wondering if you could help me change my staking    adress.   Thanks

**Comment by avrossi** [comment]
root@localhost:~# /mnt/zen/secnode/stakeaddr
-bash: /mnt/zen/secnode/stakeaddr: Permission denied

this is what Im getting

**Comment by 333miiko** [comment]
You can run the installer script again with the new stakeaddr, alternatively you simply need to edit the file (above you're trying to execute it).

Use the following command to change your stakeaddr. Note you can't use your text editor as it will leave an new line, so you must use the echo -n command

```
echo -n 'newstakeaddr' > /mnt/zen/secnode/stakeaddr
systemctl restart zen-secnodetracker
```

**Comment by avrossi** [comment]
Worked!  Thank you so much

**Comment by avrossi** [comment]
Actually is there a command to check to make sure it changed the address?

**Comment by avrossi** [comment]
Should the new stake address be in quotations or not?  I do not want to run the installer script again because i have all ready sent my 1 zen to the shielded address.  thanks again for your help..

**Comment by 333miiko** [comment]
If you get the logs of your secnode tracker you should see the new address show up there I believe:

```
docker logs zen-secnodetracker
```

**Comment by avrossi** [comment]
Thanks,
I tried that command and It gives every address other than the staking address.
any other way to find out or should i just start over...

**Comment by 333miiko** [comment]
You can put it in quotations or not, its optional. When you re-run the installer you don't lose the 1 zen you sent to the shield address.

Did you restart your zen-secnodetracker after you updated the stakeaddr?

```
cat /mnt/zen/secnode/stakeaddr
```

Does that return your new stakeaddr?

Your zen-secnodetracker log should look something like this, when your new stakeaddr is updated it will show here:

```
2017-12-06 23:58:28 GMT -- Connected to server ts1.na. Initializing...
Secure Node t_address (not for stake)=znxxx
Balance for challenge transactions is 0.9988
Using the following address for challenges
zcxxx
```

**Comment by avrossi** [comment]
Thanks again.  What's your Zencash address for donations.

**Comment by 333miiko** [comment]
No worries, glad you got it sorted!

My ZEN donation address is znZ2NFrmV6jaiq1hEnKxzApKzgGqptZNq7o

Feel free to re-open this issue if you run into any other problems.
