### ISSUE TITLE
How does this work for multiple subdomains?

### ISSUE THREAD

**Issue by adrianmcli** [WhenLamboMoon/docker-zen-node#19]
I have been successful in running the script on just a simple domain: `mydomain.com`.

But let's say I want to run `zen1.mydomain.com` and `zen2.mydomain.com` etc. How would I go about this? Do I just SSH into the VPS machine, and run the script multiple times with a different FQDN passed in? Or do I have to modify the script somehow? Will the script take care of provisioning all the subdomain certificates for me?

**Comment by 333miiko** [comment]
Each subdomain needs to have it's own VPS, so you simply run this script on each VPS and pass in the different FQDN as part of the parameters.

The script will take care of provisioning the subdomain certificate for you.

**Comment by adrianmcli** [comment]
Thanks! That explains it.
