### ISSUE TITLE
Zencash transparent address

### ISSUE THREAD

**Issue by firsttubr** [WhenLamboMoon/docker-zen-node#21]
How do I get a transparent address to send 42 zen when installing?  Can I use the address from the Zencash wallet android app?  I've tried installing Swing on my linux machine but it does not work.

**Comment by 333miiko** [comment]
I use arizen on my linux pc, this holds my 42 zen.

When the installer finishes, it gives you a shield address which unfortunately for now, you need to use the swing wallet to send the 1 ZEN to the shield address.

I installed the swing wallet on a window VM to send the 1 zen to the shield address, after that you don't need to use the swing wallet anymore

**Comment by firsttubr** [comment]
So just to clarify, you enter the transparent address from arizen when you install the zen node on the server.  Then you use swing on windows to send 1 ZEN to the shield address for the zen node.  Correct?

What happens to the 42 ZEN on arizen.  Do they just stay there?
Is the arizen address where payments get sent from the zen node?

Thanks for your help, I am new at this so I need all the advice I can get!

**Comment by 333miiko** [comment]
Yes all correct.

**Comment by firsttubr** [comment]
Thanks!  couple more questions:
do payments from the zen node get sent to the arizen address?

does arizen always need to have a minimum of 42 ZEN?

where can I get help to install arizen on linux?  I've cloned the repo on my machine but not sure where to go from there.

**Comment by 333miiko** [comment]
Yes.

Download the appimage from the release page

**Comment by 333miiko** [comment]
Feel free to re-open this issue if you have any issues.
