### ISSUE TITLE
Zero balance after sent 1 ZEN

### ISSUE THREAD

**Issue by firsttubr** [WhenLamboMoon/docker-zen-node#22]
I've installed the secure node.  I sent 1 ZEN in 4 transactions of 0.25.  Those have all been successful.  When I run the command
`docker exec zen-node gosu user zen-cli z_gettotalbalance`
I see the following:
`
{
  "transparent": "0.00",
  "private": "0.00",
  "total": "0.00"
}
`
I've waited about 10 min. Does it take more time for the 1 ZEN balance to show on my node?
thanks

**Comment by 333miiko** [comment]
Your node blockchain is probably not up to date yet,

Run this command:

```
docker exec zen-node gosu user zen-cli getinfo
```

Your blocks should be up to 218347 as of now. See http://explorer.zenmine.pro/insight/

**Comment by firsttubr** [comment]
it's showing 58375 blocks:
`
{
  "version": 2001051,
  "protocolversion": 170002,
  "walletversion": 60000,
  "balance": 0.00000000,
  "blocks": 58375,
  "timeoffset": 0,
  "connections": 9,
  "proxy": "",
  "difficulty": 22322.52116436834,
  "testnet": false,
  "keypoololdest": 1512697373,
  "keypoolsize": 101,
  "paytxfee": 0.00000000,
  "relayfee": 0.00000100,
  "errors": "WARNING: check your network connection, 0 blocks received in the last 4 hours (96 expected)"
}

`

**Comment by 333miiko** [comment]
So then your node isn't up to date, wait for it to finish updating.

**Comment by firsttubr** [comment]
Is the error  at the bottom a problem?
`WARNING: check your network connection, 0 blocks received in the last 4 hours (96 expected)`

**Comment by 333miiko** [comment]
Please Note: It may take a few hours for your server to fully update to the latest block. Your node will not come online until this has been fully updated.

You may check the latest block status with the following command:

`docker exec zen-node gosu user zen-cli getinfo`

Once your block matches the mainnet blocks then your zen should show up.

**Comment by 333miiko** [comment]
Feel free to re-open this issue if your issue is not resolved.
