### ISSUE TITLE
Zentracking values

### ISSUE THREAD

**Issue by firsttubr** [WhenLamboMoon/docker-zen-node#23]
On https://securenodes.na.zensystem.io/ I can see my node now but it shows:
Chal. Run = 0.00
CA Cert. =
Peers =
Tz Queue =

Is this normal?
thanks

**Comment by 333miiko** [comment]
I don't know why your values are empty. Challenges happen once a day, you won't get any challenge run right away.

**Comment by 333miiko** [comment]
Closing this issue due to lack of response. Feel free to reopen if you run into any other issues.
