### ISSUE TITLE
2.0.10-1

### ISSUE THREAD

**Issue by mattaero** [WhenLamboMoon/docker-zen-node#24]
It looks like they may have updated the official GitHub now with the patches, are you going to push an update, or is it unnecessary?

Thank you for everything with this, I will keep sending Zen your way :)

**Comment by 333miiko** [comment]
Doing it now, will update when it's done :)

**Comment by 333miiko** [comment]
@mattaero new build now available, again just `systemctl restart zen-node` to get the latest version.
