### ISSUE TITLE
Insufficient diskspace creates corruption

### ISSUE THREAD

**Issue by bginter** [WhenLamboMoon/docker-zen-node#26]
I ran out of disk space and zen-node exited.  I added some more but can't restart zen-node.

```
2017-12-10 21:22:46 Corruption: checksum mismatch
2017-12-10 21:22:46 : Error opening block database.
Please restart with -reindex to recover.
2017-12-10 21:22:46 Aborted block database rebuild. Exiting.
2017-12-10 21:22:46 scheduler thread interrupt
2017-12-10 21:22:46 Shutdown: In progress...
2017-12-10 21:22:46 StopRPC: waiting for async rpc workers to stop
2017-12-10 21:22:46 StopNode()
2017-12-10 21:22:46 Shutdown: done
```

What's the best way to pass that -reindex argument?

Thank you!

**Comment by 333miiko** [comment]
You will need to run the following

```
systemctl stop zen-node
docker run --rm --net=host -p 9033:9033 -p 18231:18231 -v /mnt/zen:/mnt/zen --name zen-node -it --entrypoint=/bin/bash whenlambomoon/zend:latest
gosu user zend -reindex
```

Once it finishes reindexing you can exit and restart the zen-node normally

```
# ctrl+c
exit
docker stop zen-node
systemctl restart zen-node
```

Hope this helps!

**Comment by bginter** [comment]
Thank you for the fast response!  

That didn't quite work because entrypoint.sh sets up several things first, so the gosu user command doesn't work because the "user" isn't persisted to /etc/passwd, I think, and gets setup during container startup.

I copied the initialization blocks from entrypoint.sh, created /usr/local/bin/reindex.sh and got it working.  I'll send a pull request illustrating how I was able to make this work, though you may have improvements or a better idea about how to do it.  Maybe refactor it to init.sh and source that from entrypoint.sh or reindex.sh?

I appreciate the assistance!

**Comment by 333miiko** [comment]
Ah sorry, yes you're correct. I actually think you could've just ran:

```
docker run --rm --net=host -p 9033:9033 -p 18231:18231 -v /mnt/zen:/mnt/zen --name zen-node whenlambomoon/zend:latest zend -reindex
```

This will pass the reindex to the entrypoint. Glad you got it working in the end.

**Comment by bginter** [comment]
Aha, I figured there was a simpler way. :)
