### ISSUE TITLE
Export priv key for z_address

### ISSUE THREAD

**Issue by demesm** [WhenLamboMoon/docker-zen-node#29]
Great script, working perfect. I'm just curious if/when we shutdown the node for good how to we pull the 1ZEN challenge balance out? dumpprivkeys did not work as expected!

Thank you

**Comment by 333miiko** [comment]
All your normal zen-cli keys will work, you just need to pre-append the following

```
docker exec zen-node gosu user zen-cli
```

**Comment by demesm** [comment]
![image](https://user-images.githubusercontent.com/23346713/33816714-7efabca2-de00-11e7-9d07-12dbb1e9b11e.png)

This is the output

**Comment by 333miiko** [comment]
I'm not sure if you're able to dump the private key of the shield address. 

You are able to take the wallet.dat file though and do your normal operations with that. You should find it in /mnt/zen/config/

**Comment by demesm** [comment]
Awesome thank you.

**Comment by demesm** [comment]
I imported the wallet.dat from the /mnt/zen/config to my local gui wallet and nothing showed up. I tried running the export z_wallet command and both received this err msg:

error code: -4
error message:
Cannot export wallet until the zcashd -exportdir option has been set

**Comment by 333miiko** [comment]
This is because it's a shield address not a normal transaction address. I think you will need to ask someone in the discord/slack about how to withdraw the ZEN from the shield address. I have not done this before. Sorry.

**Comment by demesm** [comment]
Is there a way via docker to add the -exportdir option?

**Comment by 333miiko** [comment]
```
systemctl stop zen-node
docker run --rm --net=host -p 9033:9033 -p 18231:18231 -v /mnt/zen:/mnt/zen --name zen-node whenlambomoon/zend:latest zend -exportdir
```

**Comment by demesm** [comment]
Upon starting it I'm just hanging at "starting zend" 
Plenty of free space/ram. I don't want to lose my zaddr since it has zen in it...!

**Comment by 333miiko** [comment]
Sorry, I'm confused, what is the issue you're having now?

**Comment by demesm** [comment]
Was hanging @ "starting zend" after running w/ -exportdir. All fixed now
