### ISSUE TITLE
Stake address

### ISSUE THREAD

**Issue by amaczen** [WhenLamboMoon/docker-zen-node#30]
docker exec zen-node gosu user zen-cli z_listaddresses        [
  "zcKhF3oX2TXiJABNXG8xmYzAQFLajNC1ZcarNVwNR1X4WvG6rE9djEnHYVTN7BfF7Nqo8jAG5z4HS22iByfLWZjW1W3TGTY",
  "zcNn9YJJk7178rcvTGBbMWXS6RvhKMmLBixGkN7kEHsaySA4EHCZ2b7Ff5r8dFtv4j6JUsp89GGFrXxjnV4ZWAWPuU2mfy9",
  "zcaVUGGatRkdZdfiyhG3opGx1WY3fnCKjEfHVfFnwiMpNzWTQNjrJsZ5yf67Fcvy1pAGcZWZ4hvDHXKw3QE3RBuGa4gPDbz"

The shielded addresses are formatted wrong?

**Comment by 333miiko** [comment]
What is wrong with their formatting? 

However I am not sure why you have 3 addresses, did you create them yourself?

**Comment by amaczen** [comment]
I created the extra addresses; maybe its an issue with my swing wallet then. Thanks for the fast reply. The wallet is saying invalid address format, it is running on the test net block chain.

**Comment by 333miiko** [comment]
this will install on the mainnet not the test net
