### ISSUE TITLE
Transfer Zen From server to new server

### ISSUE THREAD

**Issue by zammtech** [WhenLamboMoon/docker-zen-node#33]
Hi There,

The first server I set up doesn't pass the challenge consistently so I need to set up a new server on a new VPS.  How do I transfer the wallet or how do I transfer the ZEN to the new z address?  Thank you.

**Comment by 333miiko** [comment]
You could just copy the whole /mnt/zen/ folder to your new server and then re-run the installer over there. That'll bootstrap the blockchain download and copy over the wallet

**Comment by zammtech** [comment]
Thanks!

**Comment by zammtech** [comment]
One more question, does it matter that the server is in a new location using this method?  The previous was in EU now it is in NA.

**Comment by 333miiko** [comment]
It just tells your node which tracker to connect to. Ultimately there isn't much difference.

**Comment by zammtech** [comment]
I tried using FTP and SSH but I'm getting permission errors on 7 files:
scp: /mnt/zen/config/chainstate: Permission denied

**Comment by 333miiko** [comment]
Did you use root?

**Comment by zammtech** [comment]
Of course not!  Using root allowed me to transfer everything.  However it doesn't seem to work jus transferring the folder.  How can I send the coins to a new wallet via CLI?  Thanks.

**Comment by 333miiko** [comment]
You only need to transfer the wallet.dat file not all the folders.

I am not sure of the exact process of moving the ZEN out of the shield address, you may need to reach out to the community for the exact command/process.

**Comment by zammtech** [comment]
Okay.  Thank you.  I'll try again with only moving the wallet.dat.  How can I shut down the app on my first server so it doesn't interfere with the new server when it is also looking at the same 42 ZEN wallet address?

**Comment by 333miiko** [comment]
```
systemctl stop zen-node
systemctl stop zen-secnodetracker
```

This will stop the zen node and secure node tracker. In regards to the 42 zen, if it's already registered I think you'll need to send the 42 zen to a new address.

**Comment by zammtech** [comment]
Yes this is correct.  I also had an issue where it said that I needed a new z_address wallet but when trying to transfer using 
sudo docker exec zen-node gosu user zen-cli z_sendmany 'node_z-address' '[{"address": "wallet_address", "amount": x}]'
I am unable to transfer out my coin.

**Comment by 333miiko** [comment]
Glad you got this all sorted. Feel free to re-open it if you have any other issues.
