### ISSUE TITLE
can't get rid of docker

### ISSUE THREAD

**Issue by mbalance** [WhenLamboMoon/docker-zen-node#35]
Hi, I tried the script on my server without success. Now the docker keeps running/restarting and I can't get rid of it. 

`neilpang/acme.sh       "/entry.sh daemon"`

Thanks

**Comment by 333miiko** [comment]
What are you trying to achieve? Do you want to uninstall docker?

```
apt-get remove docker
```

Or just remove the container

```
docker stop zcme-sh
docker rm acme-sh
```

**Comment by mbalance** [comment]
Yes that's what I'm doing

Still keeps on restarting...

**Comment by 333miiko** [comment]
Are you looking to remove everything entirely? I would look into just doing a VPS wipe then if you are not familiar with linux? 

The docker container is being managed by a systemd

```
systemctl stop acme-sh
```

**Comment by mbalance** [comment]
That's what I needed, thanks!
