### ISSUE TITLE
Challenge results not being logged

### ISSUE THREAD

**Issue by KenJusticeJr** [WhenLamboMoon/docker-zen-node#36]
I am seeing successful challenges, however the challenge results are not being written back into the files at /mnt/zen/secnode/ .  The folder permissions are drwxrwxr-x .  Any ideas? Thank you! 
```
2017-12-16 14:33:59 GMT -- Elapsed challenge time=210  status=executing
2017-12-16 14:34:07 GMT -- Challenge submit: success
2017-12-16 14:34:07 GMT -- Challenge result:success seconds:216.173611835
challenge error
{ Error: EACCES: permission denied, open '/mnt/zen/secnode/lastExecSec.4012028749'
    at Object.fs.openSync (fs.js:646:18)
    at writeFileSync (/home/node/secnodetracker/node_modules/write-file-atomic/index.js:114:17)
    at LocalStorage.setItem (/home/node/secnodetracker/node_modules/node-localstorage/LocalStorage.js:177:7)
    at self.zenrpc.z_getoperationstatus.then.operation (/home/node/secnodetracker/SecNodeTracker.js:246:17)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/mnt/zen/secnode/lastExecSec.4012028749' }
2017-12-16 14:36:00 GMT -- Stat check: connected to:ts1.na blocks:223196 peers:12 bal:1.2492 isValidBal:true queueDepth:0 lastChalBlock:222070 lastExecSec:248.44
```

**Comment by 333miiko** [comment]
What is your base operating system? Any chance there's something like selinux running?

**Comment by KenJusticeJr** [comment]
Ubuntu 16.04.3. I ran your main installation script as a sudo user, not as root.

The node is humming along nicely...this is the only interesting behavior.

**Comment by 333miiko** [comment]
When did you run the installer? I know there were some permission issues in a very early version I published.

You could try backup the /mnt/zen/secconfig/ folder (and then delete the original). Then re-run the installer again, it should recreate the folders and pull down the latest version see if that resolves the issue.

**Comment by KenJusticeJr** [comment]
Installed it just a few days ago on December 13.

Since it is running so nicely, I am hesitant to rerun the installation script, especially now that we are into the live payout periods. I may just deal with it or find another way.

Thank you for your help!

**Comment by 333miiko** [comment]
Running the install script again should not cause any issues, you'll just get a 1 minute downtime blip.

**Comment by KenJusticeJr** [comment]
So do the following again?

curl -O https://raw.githubusercontent.com/WhenLamboMoon/docker-zen-node/master/install.sh
chmod +x install.sh
./install.sh <stakeaddr> <email> <fqdn> <region>

That won't change my shielded wallet address, the node id, or lose the zen in my shielded wallet?

**Comment by 333miiko** [comment]
Use all the same parameters you did last time, it won't generate a new shield wallet address or node id. If you want to be safe, also take a backup of /mnt/zen/config/wallet.dat before running the installer again.

**Comment by KenJusticeJr** [comment]
Ok, I'll give it a try. Thank you.

**Comment by KenJusticeJr** [comment]
Errors during installation (acme-sh, and then RPC). Now that I see this, I recall that it happened during the initial installation as well. However the node is up and running, just completed a challenge, and had the same file writing error as before. Should I be installing as root instead of a sudo user?

## Installing acme container service...


## Waiting for acme-sh to come up...

**Error response from daemon: No such container: acme-sh**
..
Main_Domain     KeyLength       SAN_Domains     Created Renew
<myfqdn>       ""      no      Sun Dec 17 00:41:47 UTC 2017    Thu Feb 15 00:41:47 UTC 2018

## Issusing cert for <myfqdn>...

[Sun Dec 17 00:51:24 UTC 2017] Domains not changed.
[Sun Dec 17 00:51:24 UTC 2017] Skip, Next renewal time is: Thu Feb 15 00:41:47 UTC 2018
[Sun Dec 17 00:51:24 UTC 2017] Add '--force' to force to renew.

## Creating the zen configuration.


## Creating the secnode config...


## Installing zend service...


## Installing secnodetracker service...


## Enabling and starting container services...


## Enabling basic firewall services...

Default outgoing policy changed to 'allow'
(be sure to update your rules accordingly)
Default incoming policy changed to 'deny'
(be sure to update your rules accordingly)
Rule updated
Rule updated (v6)
Rule updated
Rule updated (v6)
Skipping adding existing rule
Skipping adding existing rule (v6)
Skipping adding existing rule
Skipping adding existing rule (v6)
Skipping adding existing rule
Skipping adding existing rule (v6)
Firewall is active and enabled on system startup

## Enabling fail2ban services...

Synchronizing state of fail2ban.service with SysV init with /lib/systemd/systemd-sysv-install...
Executing /lib/systemd/systemd-sysv-install enable fail2ban

## Waiting for node to fetch params ...

**error: couldn't connect to server: unknown (code -1)
(make sure server is running and you are connecting to the correct RPC port)**
..
{
  "version": 2001051,
  "protocolversion": 170002,
  "walletversion": 60000,
  "balance": 0.00000000,
  "blocks": 223445,
  "timeoffset": 0,
  "connections": 1,
  "proxy": "",
  "difficulty": 554510.2451746175,
  "testnet": false,
  "keypoololdest": 1513204547,
  "keypoolsize": 101,
  "paytxfee": 0.00000000,
  "relayfee": 0.00000100,
  "errors": ""
}

## Node already has shield address... you will need to send 1 ZEN to this address:

[
  "<myshieldedaddress>"
]

## Install Finished

Please wait until the blocks are up to date...

**Comment by 333miiko** [comment]
acme-sh and RPC related errors are just checks to see if they're running, the next attempt it succeeds so they are harmless error notices.

The installer should be run as root. Did you backup and then delete the /mnt/zen/secnode/ before re-running the installer?

**Comment by KenJusticeJr** [comment]
Understood about acme-sh and RPC. Thank you.

Yes, I had deleted /mnt/zen/secnode/ before re-running the installer.

I tried it again, this time running the installer as root (first deleted /mnt/zen/secnode/ ). The node came up properly and successfully executed a challenge. I received a similar error at the end though.

2017-12-17 23:36:35 GMT -- Elapsed challenge time=200  status=executing
2017-12-17 23:36:36 GMT -- Challenge submit: success
2017-12-17 23:36:36 GMT -- Challenge result:success seconds:200.60018982
challenge error
{ Error: EACCES: permission denied, open '/home/node/secnodetracker/config/lastExecSec.4012028749'
    at Object.fs.openSync (fs.js:646:18)
    at writeFileSync (/home/node/secnodetracker/node_modules/write-file-atomic/index.js:114:17)
    at LocalStorage.setItem (/home/node/secnodetracker/node_modules/node-localstorage/LocalStorage.js:177:7)
    at self.zenrpc.z_getoperationstatus.then.operation (/home/node/secnodetracker/SecNodeTracker.js:246:17)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/home/node/secnodetracker/config/lastExecSec.4012028749' }

The strange thing is that there is no such folder as /home/node/...  Could this be the problem?

**Comment by 333miiko** [comment]
/mnt/zen/secnode/ is copied to /home/node/secnodetracker inside the container.

Could you try run this and let me know the output:

```
docker exec -it zen-secnodetracker
cd /home/node/
ls -al
touch secnodetracker/test
rm secnodetracker/test

gosu user touch secnodetracker/test
rm secnodetracker/test
```

**Comment by KenJusticeJr** [comment]
It does not take the first command.

`root@z-e-n-sec-ubuntu-1:~# docker exec -it zen-secnodetracker
"docker exec" requires at least 2 argument(s).
See 'docker exec --help'.

Usage:  docker exec [OPTIONS] CONTAINER COMMAND [ARG...]

Run a command in a running container
`

**Comment by 333miiko** [comment]
Sorry first command

```
docker exec -it zen-secnodetracker bash
```

**Comment by KenJusticeJr** [comment]
root@z-e-n-sec-ubuntu-1:~# docker exec -it zen-secnodetracker bash
root@z-e-n-sec-ubuntu-1:/# cd /home/node
root@z-e-n-sec-ubuntu-1:/home/node# ls -al
total 24
drwxr-xr-x 4 node node 4096 Dec 17 23:47 .
drwxr-xr-x 5 root root 4096 Dec 17 23:47 ..
-rw-r--r-- 1 node node  220 Nov  5  2016 .bash_logout
-rw-r--r-- 1 node node 3515 Nov  5  2016 .bashrc
-rw-r--r-- 1 node node  675 Nov  5  2016 .profile
drwxr-xr-x 4 root root 4096 Dec 17 23:47 secnodetracker
root@z-e-n-sec-ubuntu-1:/home/node# touch secnodetracker/test
root@z-e-n-sec-ubuntu-1:/home/node# rm secnodetracker/test
root@z-e-n-sec-ubuntu-1:/home/node# gosu user touch secnodetracker/test
error: failed switching to "user": unable to find user user: no matching entries in passwd file
root@z-e-n-sec-ubuntu-1:/home/node# rm secnodetracker/test
rm: cannot remove 'secnodetracker/test': No such file or directory

**Comment by KenJusticeJr** [comment]
Something interesting just occurred. A challenge request was received, and now there is no error message on the log. I have done nothing in the meantime except issue the commands that you had requested above.

```
2017-12-18 23:45:59 GMT -- Elapsed challenge time=200  status=executing
2017-12-18 23:46:09 GMT -- Elapsed challenge time=210  status=success
2017-12-18 23:46:09 GMT -- Challenge submit: success
2017-12-18 23:46:09 GMT -- Challenge result:success seconds:209.162645628
2017-12-18 23:46:11 GMT -- Clearing timer
2017-12-18 23:47:22 GMT -- Stat check: connected to:ts1.na blocks:224559 peers:10 bal:1.2486 isValidBal:false queueDepth:0 lastChalBlock:224558 lastExecSec:209.16
```

**Comment by 333miiko** [comment]
Ok I found the issue, can you try run `systemctl restart zen-secnodetracker` in about 20 minutes. This should upgrade to the latest version. This should resolve your issue.

**Comment by KenJusticeJr** [comment]
Seems to have worked. Thank you! I'll be sending you a donation.

**Comment by 333miiko** [comment]
Glad we got it sorted, all the best. Feel free to re-open this if you run into any other issues.

**Comment by KenJusticeJr** [comment]
Drat, it's happening again. The only thing that I have done is reboot the server, to resolve high memory usage and troubleshoot the erroneous down time logs that many nodes have been getting hit with.

```
2017-12-20 01:39:48 GMT -- Elapsed challenge time=200  status=executing
2017-12-20 01:39:54 GMT -- Challenge submit: success
2017-12-20 01:39:54 GMT -- Challenge result:success seconds:204.516269578
challenge error
{ Error: EACCES: permission denied, open '/mnt/zen/secnode/lastExecSec.4012028749'
    at Object.fs.openSync (fs.js:646:18)
    at writeFileSync (/home/node/secnodetracker/node_modules/write-file-atomic/index.js:114:17)
    at LocalStorage.setItem (/home/node/secnodetracker/node_modules/node-localstorage/LocalStorage.js:177:7)
    at self.zenrpc.z_getoperationstatus.then.operation (/home/node/secnodetracker/SecNodeTracker.js:246:17)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/mnt/zen/secnode/lastExecSec.4012028749' }
2017-12-20 01:40:38 GMT -- Stat check: connected to:ts1.na blocks:225179 peers:10 bal:0.9986 isValidBal:true queueDepth:0 lastChalBlock:224598 lastExecSec:192.89
2017-12-20 01:46:38 GMT -- Stat check: connected to:ts1.na blocks:225180 peers:10 bal:1.2482 isValidBal:true queueDepth:0 lastChalBlock:224598 lastExecSec:192.89
```

**Comment by 333miiko** [comment]
This last line sorry should be:

```
gosu node touch secnodetracker/test
```

**Comment by 333miiko** [comment]
The 85% memory usage issue is being tracked upstream https://github.com/ZencashOfficial/zen/issues/86

**Comment by 333miiko** [comment]
Could you also list the permissions of this folder:

```
ls -al /mnt/zen/
ls -al /mnt/zen/secnodetracker/
```

**Comment by KenJusticeJr** [comment]
Should the last command be ls -al /mnt/zen/secnode/  instead? There is no /mnt/zen/secnodetracker folder. Here are the results.

```
root@z-e-n-sec-ubuntu-1:~# docker exec -it zen-secnodetracker bash
root@z-e-n-sec-ubuntu-1:/# cd /home/node
root@z-e-n-sec-ubuntu-1:/home/node# ls -al
total 24
drwxr-xr-x 4 node node 4096 Dec 19 12:04 .
drwxr-xr-x 5 root root 4096 Dec 19 12:04 ..
-rw-r--r-- 1 node node  220 Nov  5  2016 .bash_logout
-rw-r--r-- 1 node node 3515 Nov  5  2016 .bashrc
-rw-r--r-- 1 node node  675 Nov  5  2016 .profile
drwxr-xr-x 6 node node 4096 Dec 20 01:56 secnodetracker
root@z-e-n-sec-ubuntu-1:/home/node# touch secnodetracker/test
root@z-e-n-sec-ubuntu-1:/home/node# rm secnodetracker/test
root@z-e-n-sec-ubuntu-1:/home/node# gosu node touch secnodetracker/test
root@z-e-n-sec-ubuntu-1:/home/node# rm secnodetracker/test
root@z-e-n-sec-ubuntu-1:/home/node# ls -al /mnt/zen/
total 32
drwxr-xr-x 8 9001 9001 4096 Dec 17 23:49 .
drwxr-xr-x 4 root root 4096 Dec 19 12:04 ..
drwxr-xr-x 4 9001 9001 4096 Dec 17 00:41 certs
drwxr-xr-x 5 9001 9001 4096 Dec 20 14:10 config
drwxr-xr-x 2 9001 9001 4096 Dec 17 00:41 data
drwxrwxr-x 2 9001 9001 4096 Dec 19 01:29 secnode
drwxr-xr-x 2 9001 9001 4096 Dec 17 23:22 secnode.backup
drwxr-xr-x 2 9001 9001 4096 Dec 17 00:42 zcash-params
root@z-e-n-sec-ubuntu-1:/home/node# ls -al /mnt/zen/secnodetracker/
ls: cannot access /mnt/zen/secnodetracker/: No such file or directory
root@z-e-n-sec-ubuntu-1:/home/node# cd /mnt/zen
root@z-e-n-sec-ubuntu-1:/mnt/zen# ls
certs  config  data  secnode  secnode.backup  zcash-params
root@z-e-n-sec-ubuntu-1:/mnt/zen# ls -al /mnt/zen/secnode
total 68
drwxrwxr-x 2 9001 9001 4096 Dec 19 01:29 .
drwxr-xr-x 8 9001 9001 4096 Dec 17 23:49 ..
-rw-r--r-- 1 9001 9001   25 Dec 17 23:25 email
-rw-r--r-- 1 9001 9001   25 Dec 17 23:25 fqdn
-rw-r--r-- 1 9001 9001    6 Dec 17 23:25 home
-rw-r--r-- 1 9001 9001    6 Dec 19 01:29 lastChalBlock
-rw-r--r-- 1 9001 9001    6 Dec 19 01:29 lastExecSec
-rw-r--r-- 1 9001 9001    4 Dec 17 23:26 nodeid
-rw-r--r-- 1 9001 9001    2 Dec 17 23:25 region
-rw-r--r-- 1 9001 9001    9 Dec 17 23:25 rpcallowip
-rw-r--r-- 1 9001 9001    9 Dec 17 23:25 rpcbind
-rw-r--r-- 1 9001 9001   44 Dec 17 23:25 rpcpassword
-rw-r--r-- 1 9001 9001    5 Dec 17 23:25 rpcport
-rw-r--r-- 1 9001 9001    4 Dec 17 23:25 rpcuser
-rw-r--r-- 1 9001 9001   21 Dec 17 23:25 servers
-rw-r--r-- 1 9001 9001   31 Dec 17 23:25 serverurl
-rw-r--r-- 1 9001 9001   35 Dec 17 23:25 stakeaddr
```

**Comment by 333miiko** [comment]
Did you run these commands from within the container? This should be showing the "node" user. I'm not sure why the issue would still be persisting for you, the patch I applied fixed the issue on my nodes.

```
docker exec -it zen-secnodetracker bash
chown -R node:node /mnt/zen/secnode /mnt/zcash-params /home/node/secnodetracker
chmod g+rw /mnt/zen/secnode /home/node/secnodetracker
```

This should definitely fix the issue.

**Comment by KenJusticeJr** [comment]
Yes, I had done them from within the container.

I applied your latest commands. That worked. Thank you!
