### ISSUE TITLE
Ansible installer co-location of servers

### ISSUE THREAD

**Issue by KenJusticeJr** [WhenLamboMoon/docker-zen-node#39]
Does the ansible installer require that the servers be privately networked together first? That is, if I am creating multiple VPS instances, do they need to be in the same server location, or can they be geographically dispersed? Thank you.

**Comment by 333miiko** [comment]
No, your "installer" just needs to have SSH access to all your other servers.

So what I do is setup my first node, and then generate a ssh key on there

```
ssh-keygen
```

Grab the public key:

```
cat ~/.ssh/id_rsa.pub
```

Depending on your VPS provider, they should allow you to inject a SSH key into your new VPS instance on installation.

One other thing you'll need to do this https://stackoverflow.com/questions/23074412/how-to-set-host-key-checking-false-in-ansible-inventory-file

Now when you run the installer on the "install" server, it'll have free access to login to all the servers using the SSH public key and complete the installation.

Just remember to backup this SSH key you generate if it is the only one you will install.

**Comment by KenJusticeJr** [comment]
I'll give it a shot. Thank you.
