### ISSUE TITLE
Can't get it to run

### ISSUE THREAD

**Issue by slayorktc** [WhenLamboMoon/docker-zen-node#4]
Having some trouble getting your docker to run. During the install, I got these messages, which I am not sure how to resolve.

## Waiting for acme-sh to come up...

Error response from daemon: No such container: acme-sh

## Waiting for node to fetch params ...

Error response from daemon: No such container: zen-node

UPDATE: Nevermind, looking at the code again, i see you wait until the docker comes back up and that is why those messages show up. 

I get it to the install finished but how do I debug the state of the secureNodeTracker software? Node doesn't seem to be installed. Everything looks like it should work, but doesn't display on the zen node tracking page. 

Also, in the entrypoint.sh, i noticed this line: gosu node node app.js

Should it be: gosu user node app.js
instead?

when i run zend inside the docker image, i get this message:

仕方が無い
Shikata ga nai.
它不能得到帮助

Since starting this node 0 seconds ago:
- You have validated no transactions.

Messages:
Error: Cannot find the Zcash network parameters in the following directory:
"/root/.zcash-params"
Please run 'zen-fetch-params' or './zcutil/fetch-params.sh' and then restart.

Init message: Loading block index...

**Comment by slayorktc** [comment]
Nov 13 01:34:45 localhost systemd[1]: Started Zen Secnodetracker Container.
Nov 13 01:34:45 localhost docker[4762]: Secure node config found OK - linking...
Nov 13 01:34:46 localhost docker[4762]: chown: cannot access '/mnt/zcash-params': No such file or directory
Nov 13 01:34:47 localhost docker[4762]: fs.js:885
Nov 13 01:34:47 localhost docker[4762]:   return binding.mkdir(pathModule._makeLong(path),
Nov 13 01:34:47 localhost docker[4762]:                  ^
Nov 13 01:34:47 localhost docker[4762]: Error: EACCES: permission denied, mkdir '/secnodetracker/config'
Nov 13 01:34:47 localhost docker[4762]:     at Object.fs.mkdirSync (fs.js:885:18)
Nov 13 01:34:47 localhost docker[4762]:     at LocalStorage._init (/secnodetracker/node_modules/node-localstorage/LocalStorage.js:151:12)
Nov 13 01:34:47 localhost docker[4762]:     at new LocalStorage (/secnodetracker/node_modules/node-localstorage/LocalStorage.js:121:12)
Nov 13 01:34:47 localhost docker[4762]:     at Object.<anonymous> (/secnodetracker/SecNodeTracker.js:3:15)
Nov 13 01:34:47 localhost docker[4762]:     at Module._compile (module.js:635:30)
Nov 13 01:34:47 localhost docker[4762]:     at Object.Module._extensions..js (module.js:646:10)
Nov 13 01:34:47 localhost docker[4762]:     at Module.load (module.js:554:32)
Nov 13 01:34:47 localhost docker[4762]:     at tryModuleLoad (module.js:497:12)
Nov 13 01:34:47 localhost docker[4762]:     at Function.Module._load (module.js:489:3)
Nov 13 01:34:47 localhost docker[4762]:     at Module.require (module.js:579:17)
Nov 13 01:34:47 localhost systemd[1]: zen-secnodetracker.service: Main process exited, code=exited, status=1/FAILURE
Nov 13 01:34:47 localhost systemd[1]: zen-secnodetracker.service: Unit entered failed state.
Nov 13 01:34:47 localhost systemd[1]: zen-secnodetracker.service: Failed with result 'exit-code'.

**Comment by rloomba** [comment]
@slayorktc there seems to be a typo, the zcash-params is actually located at `/mnt/znode/zcash-params`, not at `/mnt/zcash-params`

**Comment by slayorktc** [comment]
Did that get updated in your repo?

**Comment by rloomba** [comment]
@slayorktc no. You can either update the [this file](https://github.com/WhenLamboMoon/docker-zen-node/blob/master/secnodetracker/entrypoint.sh#L13) and change it to `/mnt/zen/zcash-params` and rebuild docker image

or lazy way would be to

`cp -r /mnt/zen/zcash-params /mnt/zcash-params ` on an existing running system.

**Comment by slayorktc** [comment]
Cool. Ill give that a shot and see if that fixes the issue.

**Comment by 333miiko** [comment]
`node is the username that's created in the official node image so that's why it's `gosu node node app.js` for secnodetracker

I updated your fixes. Sorry I'm travelling right now so been a bit hard to keep up.

**Comment by slayorktc** [comment]
Pulled down a clean repo and running. Getting some errors:
## Waiting for node to fetch params ...

error: couldn't connect to server: unknown (code -1)
(make sure server is running and you are connecting to the correct RPC port)
..
rpc error: code = 13 desc = invalid header field value "oci runtime error: exec failed: cannot exec a container that has run and stopped\n"
..
error: couldn't connect to server: unknown (code -1)
(make sure server is running and you are connecting to the correct RPC port)
..
Error response from daemon: No such container: zen-node
..
error: failed switching to "user": unable to find user user: no matching entries in passwd file
..
error: failed switching to "user": unable to find user user: no matching entries in passwd file
..
Error response from daemon: No such container: zen-node
..
error: couldn't connect to server: unknown (code -1)
(make sure server is running and you are connecting to the correct RPC port)
..
error: couldn't connect to server: unknown (code -1)
(make sure server is running and you are connecting to the correct RPC port)
..
error: failed switching to "user": unable to find user user: no matching entries in passwd file
..
error: failed switching to "user": unable to find user user: no matching entries in passwd file
..
Error response from daemon: Container 9d751b025b94f9615003dc6668a64330fab1846e6a339029854bfb3560c41170 is not running
..
error: failed switching to "user": unable to find user user: no matching entries in passwd file
..
error: couldn't connect to server: unknown (code -1)
(make sure server is running and you are connecting to the correct RPC port)
..
Error response from daemon: No such container: zen-node



Sounds like your busy, so I will give it some debugging. If you know the solution, please chime in though. :)

**Comment by slayorktc** [comment]
Think I got passed the first issue but looking at the logs, I am getting this error:

chown: invalid user: 'user:user'
fs.js:885
  return binding.mkdir(pathModule._makeLong(path),
                 ^

Error: EACCES: permission denied, mkdir '/secnodetracker/config'
    at Object.fs.mkdirSync (fs.js:885:18)
    at LocalStorage._init (/secnodetracker/node_modules/node-localstorage/LocalStorage.js:151:12)
    at new LocalStorage (/secnodetracker/node_modules/node-localstorage/LocalStorage.js:121:12)
    at Object.<anonymous> (/secnodetracker/SecNodeTracker.js:3:15)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)

**Comment by slayorktc** [comment]
Hmm not sure what is going on but the docker images are restarting every 10 minutes. Not sure how to tell what is making them crash or what is going on. Did your latest changes work on your server?

**Comment by rloomba** [comment]
I was not able to get the secnodetracker working via the docker container, I pulled from https://github.com/WhenLamboMoon/docker-zen-node/commit/4c7fc836390d0b217ccffd4ab9ee4ff7145a83c1.

I ended up just installing and running the service via pm2. When I have some more time, I was hoping to debug the problem.

**Comment by slayorktc** [comment]
Interesting. I will give it a shot tomorrow with fresh eyes and try to get it all working as well.

**Comment by 333miiko** [comment]
The new build should fix your permission issue. Let me know if that fixes it. I should have some spare time in the next few days to do some more extensive testing and bug fixes.

**Comment by slayorktc** [comment]
Synchronizing state of fail2ban.service with SysV init with /lib/systemd/systemd-sysv-install...
Executing /lib/systemd/systemd-sysv-install enable fail2ban

## Waiting for node to fetch params ...

Error response from daemon: No such container: zen-node
..
error: couldn't connect to server: unknown (code -1)
(make sure server is running and you are connecting to the correct RPC port)
..
error: couldn't connect to server: unknown (code -1)
(make sure server is running and you are connecting to the correct RPC port)
..
Error response from daemon: No such container: zen-node
..
Error reading configuration file: Missing zcash.conf
..
Error response from daemon: No such container: zen-node
..
Error response from daemon: Container 406ab33cd2c93139cb7ded12af853e7a2f523eba492d960bcd881b8b0db6c27b is not running
..
Error response from daemon: Container bba6293b6b512e53323b7820a2a0b577549efd6b134745263947e634e0eb3e35 is not running
..
rpc error: code = 2 desc = containerd: container not found
..
^C

**Comment by slayorktc** [comment]
Similar issue. The zen-node doesn't appear to be coming up online. I pulled your latest repo. Not sure if it was because I just deleted the previous github directory and cloned it again and ran install. I figured I would blow away my VM instance and pull to a clean VM and see if that runs.

**Comment by slayorktc** [comment]
Spun up a brand new clean VPS and tried your repo. The install script hung right here:
## Enabling and starting container services...

Created symlink from /etc/systemd/system/multi-user.target.wants/zen-node.service to /etc/systemd/system/zen-node.service.

I will let it sit and see if it gets passed it but right now it looks hung.

**Comment by slayorktc** [comment]
Synchronizing state of fail2ban.service with SysV init with /lib/systemd/systemd-sysv-install...
Executing /lib/systemd/systemd-sysv-install enable fail2ban

## Waiting for node to fetch params ...

Error response from daemon: No such container: zen-node
..
Error response from daemon: No such container: zen-node
..
Error response from daemon: No such container: zen-node
..
Moved passed but now stopped at this. Letting it go for awhile and see if it gets past it.

**Comment by slayorktc** [comment]
## Enabling and starting container services...

Job for zen-node.service failed because a timeout was exceeded. See "systemctl status zen-node.service" and "journalctl -xe" for details.

**Comment by 333miiko** [comment]
Should come up now

**Comment by slayorktc** [comment]
Best results yet! I just spun up a new VM and pulled down the latest repo and the install appeared to complete and the zend is up and running. Going to do some more testing tomorrow and make sure everything is solid. If we're good I'll close the ticket.

**Comment by slayorktc** [comment]
Nov 19 01:40:48 localhost systemd[1]: Started Zen Secnodetracker Container.
Nov 19 01:40:48 localhost docker[18468]: Secure node config found OK - linking...
Nov 19 01:41:06 localhost docker[18468]: CPU Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz  cores=1  speed=2499
Nov 19 01:41:06 localhost docker[18468]: Tracker app version: 0.0.8
Nov 19 01:41:06 localhost docker[18468]: MemTotal: 0.99GB  MemFree: 0.12GB  MemAvailable: 0.56GB  SwapTotal: 4.35GB  SwapFree: 4.04GB
Nov 19 01:41:06 localhost docker[18468]: 2017-11-19 01:41:06 GMT -- Connected to server ts1.na. Initializing...
Nov 19 01:41:06 localhost docker[18468]: Secure Node t_address=ztqa6Cfx1hpcFtM5dTnDmsAX8XsQPCEKpzP
Nov 19 01:41:06 localhost docker[18468]: Balance for challenge transactions is 1.4
Nov 19 01:41:06 localhost docker[18468]: Using the following address for challenges
Nov 19 01:41:06 localhost docker[18468]: ztWFbvkazu8ae88j3Vzz92fcm86p1bAnm8CTRR9c7xYSorT8ZWuPDygh38ksN5vgReNGrABjmzS6kaE57g1WudhJJVUVDJ8
Nov 19 01:41:06 localhost docker[18468]: /home/node/secnodetracker/node_modules/write-file-atomic/index.js:127
Nov 19 01:41:06 localhost docker[18468]:     throw err
Nov 19 01:41:06 localhost docker[18468]:     ^
Nov 19 01:41:06 localhost docker[18468]: Error: EACCES: permission denied, open '/home/node/secnodetracker/config/nodeid.2793788270'
Nov 19 01:41:06 localhost docker[18468]:     at Object.fs.openSync (fs.js:646:18)
Nov 19 01:41:06 localhost docker[18468]:     at writeFileSync (/home/node/secnodetracker/node_modules/write-file-atomic/index.js:114:17)
Nov 19 01:41:06 localhost docker[18468]:     at LocalStorage.setItem (/home/node/secnodetracker/node_modules/node-localstorage/LocalStorage.js:177:7)
Nov 19 01:41:06 localhost docker[18468]:     at Socket.socket.on (/home/node/secnodetracker/app.js:157:11)
Nov 19 01:41:06 localhost docker[18468]:     at Socket.Emitter.emit (/home/node/secnodetracker/node_modules/component-emitter/index.js:133:20)
Nov 19 01:41:06 localhost docker[18468]:     at Socket.onevent (/home/node/secnodetracker/node_modules/socket.io-client/lib/socket.js:270:10)
Nov 19 01:41:06 localhost docker[18468]:     at Socket.onpacket (/home/node/secnodetracker/node_modules/socket.io-client/lib/socket.js:228:12)
Nov 19 01:41:06 localhost docker[18468]:     at Manager.<anonymous> (/home/node/secnodetracker/node_modules/component-bind/index.js:21:15)
Nov 19 01:41:06 localhost docker[18468]:     at Manager.Emitter.emit (/home/node/secnodetracker/node_modules/component-emitter/index.js:133:20)
Nov 19 01:41:06 localhost docker[18468]:     at Manager.ondecoded (/home/node/secnodetracker/node_modules/socket.io-client/lib/manager.js:345:8)
Nov 19 01:41:06 localhost docker[18468]:     at Decoder.<anonymous> (/home/node/secnodetracker/node_modules/component-bind/index.js:21:15)
Nov 19 01:41:06 localhost docker[18468]:     at Decoder.Emitter.emit (/home/node/secnodetracker/node_modules/component-emitter/index.js:133:20)
Nov 19 01:41:06 localhost docker[18468]:     at Decoder.add (/home/node/secnodetracker/node_modules/socket.io-parser/index.js:241:12)
Nov 19 01:41:06 localhost docker[18468]:     at Manager.ondata (/home/node/secnodetracker/node_modules/socket.io-client/lib/manager.js:335:16)
Nov 19 01:41:06 localhost docker[18468]:     at Socket.<anonymous> (/home/node/secnodetracker/node_modules/component-bind/index.js:21:15)
Nov 19 01:41:06 localhost docker[18468]:     at Socket.Emitter.emit (/home/node/secnodetracker/node_modules/component-emitter/index.js:133:20)
Nov 19 01:41:06 localhost systemd[1]: zen-secnodetracker.service: Main process exited, code=exited, status=1/FAILURE
Nov 19 01:41:06 localhost systemd[1]: zen-secnodetracker.service: Unit entered failed state.
Nov 19 01:41:06 localhost systemd[1]: zen-secnodetracker.service: Failed with result 'exit-code'.


Are you getting this error with the secnodetracker? Might just do another clean vm and see if that error goes away.

**Comment by slayorktc** [comment]
Definitely having issues fixing this. The docker crashes so fast that I can't get inside with exec to poke around. 

Nov 19 01:41:06 localhost docker[18468]: Error: EACCES: permission denied, open '/home/node/secnodetracker/config/nodeid.2793788270'

**Comment by 333miiko** [comment]
If you want to exec to poke around you should

```
systemctl stop zen-secnodetracker
docker run --rm  -v /mnt/zen:/mnt/zen -it --entrypoint=/bin/bash --name secnode whenlambomoon/secnodetracker
```

**Comment by 333miiko** [comment]
https://github.com/WhenLamboMoon/docker-zen-node/blob/master/secnodetracker/entrypoint.sh#L16 should be setting the right permissions and it worked for me during my test.

**Comment by slayorktc** [comment]
I used that command to go into /home/node/secnodetracker, changed the ownership to node:node then ran node setup.js. Dropped everything in it was asking for but at the end I got this message:

Region code - North America(na) Europe(eu) Southeast Asia(sea)  (Default: na): 
Retrieving zen rpc config....
ERROR: Region code  Cannot read property 'pop' of undefined

Not sure why it is getting 'pop' when I defined na. 

Have you tried running the install script twice? Not sure if that is where this error is coming from. Also, can I run a docker command with the entrypoint.sh script for secnodetracker and a /bin/bash so I can see what the enviroment looks like? I want to make sure the entrypoint is setting the permissions and ownerships correctly.

I could always blow away this VM and start from scratch but how do I go about backing up the shielded address wallet? I just need to backup the wallet.dat file inside the zend directory, correct? How do I pull that file out of the docker container?

Have to run but will continue messing with this when I get back.

**Comment by 333miiko** [comment]
Everything you want to backup would be in /mnt/zen

I'll check this again, my nodes don't seem to be having any issues.

**Comment by 333miiko** [comment]
Pushed a few more fixes, your container should auto update. I've deployed another node without any issues.

**Comment by slayorktc** [comment]
Excellent! Pulled down your latest repo and everything seems to be rocking! Awesome work! Ill toss some zen your way!

**Comment by 333miiko** [comment]
Awesome, glad we got this working :smile: All the best. Feel free to open another issue if you run into any other problems.
