### ISSUE TITLE
Proper docker repo

### ISSUE THREAD

**Issue by Alwinius** [WhenLamboMoon/docker-zen-node#40]
I would suggest to install docker from the official repo
https://docs.docker.com/engine/installation/linux/docker-ce/ubuntu/#install-using-the-repository

**Comment by 333miiko** [comment]
That would've been a good idea. 

Currently we don't need the latest version of Docker and it will take a bit of extra work to preserve the backwards compatibility of existing hosts. Happy to accept a PR if you think this is necessary.
