### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by amaczen** [WhenLamboMoon/docker-zen-node#41]
What is the command to dump my private keys? and how can I view them on cli. thanks in advance

**Comment by 333miiko** [comment]
You need to pre-append the following to run any `zen-cli` command:

```
docker exec zen-node gosu user zen-cli
```

**Comment by amaczen** [comment]
I used that command followed by exportkey then my shielded address. this gave me an error? the node has been running for a week.

**Comment by 333miiko** [comment]
What error did you get?

**Comment by amaczen** [comment]
root@vps489949:~# docker exec zen-node gosu user zen-cli exportkey zcLqwf2xhchpFbHS4G7UpwVoSthrPLh45nGZnFaeAK3Xdf5R8oEn66rs38nurCDZYtP9odaYGfxDYo2P7bGRiRwoYayXmPu
error code: -32601
error message:
Method not found

**Comment by amaczen** [comment]
I missed z_exportkey . fixed
