### ISSUE TITLE
How do i change my region?

### ISSUE THREAD

**Issue by avrossi** [WhenLamboMoon/docker-zen-node#43]
Hope all is well. I need to change my region because I am set up on SEA and apparentlly its gone. Now what do I do?
Thanks!

**Comment by 333miiko** [comment]
What do you mean its gone?

If you want to change your region you need to run the following:

```
region=na
echo -n "ts1.$region" > /mnt/zen/secnode/home
echo -n $region > /mnt/zen/secnode/region
systemctl restart zen-secnodetracker
```

**Comment by avrossi** [comment]
What I mean is on the ZenCash Secure Nodes Tracking system they have removed the SEA region all together. My VPN is in Japan and is setup for SEA.  If i run the command you provided will this fix the issue or do i need to make changes to my VPN? Thanks

**Comment by 333miiko** [comment]
Oh I wasn't aware they removed the SEA region. 

Did it fix your issues?

**Comment by avrossi** [comment]
Yes that command changed my region to NA successfully.  The problem I am having now is that on my down times log it says that I am in a downtime since I made the change.  But the odd thing is that my node state is UP and I am completing challenges.  My node is binkernode.com  
Thanks

**Comment by 333miiko** [comment]
Send yourself a challenge and see if the issue resolves itself. You can also try restart your whole VPS to trigger a new "downtime". However if you're passing challenges and its showing your node status is UP it should be ok.

**Comment by avrossi** [comment]
I restarted the VPS and triggered a new "downtime"  and that did the trick.  Thanks again
