### ISSUE TITLE
Unhandled rejection Error: ESOCKETTIMEDOUT - Unable to collect stats without a nodeid.

### ISSUE THREAD

**Issue by rsqu4red** [WhenLamboMoon/docker-zen-node#44]
Hello,
first of all Thank you so much for the Work you put in the code here. Worked like a charm so far. I set everything up, but at the final steps I encountered a Problem. All my attemps to fix the problem failed so far. Maybe you could help me setting up the secure node.
Balance for Shield-Adress is 1 ZEN. The Stakeadress has more than 42 ZEN in it.
Just had an idea: I don't know if I put a transparent adress or a private adress in as an Stakeadress for the installation - Could that be the Problem?
How can I get the 1 ZEN from the Shield-Adress back in my wallet?

**The following is showing:**

root@vmdXXXXX:~# docker logs zen-secnodetracker

Output:

Secure node config found OK - linking...
CPU Intel(R) Xeon(R) CPU E5-2620 v2 @ 2.10GHz  cores=2  speed=2099
Tracker app version: 0.1.0
MemTotal: 5.97GB  MemFree: 2.58GB  MemAvailable: 4.81GB  SwapTotal: 0.00GB  SwapFree: 0.00GB  
2017-12-31 02:59:52 GMT -- Connected to server ts1.eu. Initializing...
Secure Node t_address (not for stake)=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Unhandled rejection Error: ESOCKETTIMEDOUT
    at ClientRequest.<anonymous> (/home/node/secnodetracker/node_modules/request/request.js:813:19)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at ClientRequest.emit (events.js:208:7)
    at Socket.emitTimeout (_http_client.js:708:34)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:407:8)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
2017-12-31 03:05:52 GMT -- Unable to collect stats without a nodeid.
2017-12-31 03:11:52 GMT -- Unable to collect stats without a nodeid.
2017-12-31 03:17:52 GMT -- Unable to collect stats without a nodeid.
2017-12-31 03:23:52 GMT -- Unable to collect stats without a nodeid.
2017-12-31 03:29:52 GMT -- Unable to collect stats without a nodeid.
2017-12-31 03:35:52 GMT -- Unable to collect stats without a nodeid.
2017-12-31 03:41:52 GMT -- Unable to collect stats without a nodeid.
2017-12-31 03:47:52 GMT -- Unable to collect stats without a nodeid.
2017-12-31 03:53:52 GMT -- Unable to collect stats without a nodeid.
2017-12-31 03:59:52 GMT -- Unable to collect stats without a nodeid.
2017-12-31 04:05:52 GMT -- Unable to collect stats without a nodeid.
2017-12-31 04:11:52 GMT -- Unable to collect stats without a nodeid.
and some more lines with the time....

**AND**

root@vmd24481:~# docker logs zen-node

Output:

Starting with UID/GID : 9001/9001
Symlinking external zcash-params volume...
Using external data volume
Copying additional trusted SSL certificates
Clearing symlinks in /etc/ssl/certs...
done.
Updating certificates in /etc/ssl/certs...
149 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.
Zcash - fetch-params.sh

Zen uses the same zkSNARK parameters generated by ZCash.
This script will fetch the Zcash zkSNARK parameters and verify their
integrity with sha256sum.

If they already exist locally, it will exit now and do nothing else.
Starting zend ..

**Do you know what the Problem is?**

Thanks so much

**Comment by 333miiko** [comment]
Can you run the following commands and see if it fixes the issue, looks
like the securenode tracker didn't provide you with a nodeid

```
systemctl restart zen-node
systemctl restart zen-secnodetracker
```

**Comment by rsqu4red** [comment]
Hi Miiko,
thanks for the quick reply.
Seems to have worked! Excellent! Thank you very much.
The node is now listed on: https://securenodes.eu.zensystem.io/ - I am just waiting 1 or 2 days to see if the adess is eligible for a paiout. 
As I am new just a few more questions I couldn't get the answer to yet.

- Once I dont want to run the secure node anymore - Is it possible to get the 1 ZEN from the shieldadress back? How would that be possible.
- Does it need 1 ZEN? https://securenodes.eu.zensystem.io/about Here it says: "Must maintain a minimum balance of .001 ZEN in a private address on the node for challenges"
- The payments are sent approx. daily to the transparent/private address where the 42 zen are held?

Thanks a lot :)

**Comment by 333miiko** [comment]
I believe the command to move your zen is something like:

zen-cli z_sendmany "T_ADDR" "[{\"amount\": 0.00, \"address\":
\"TO_ZEN_ADDR\"}]"

The 1 ZEN is just an arbitrary value people recommend since it'll last a
very very long time.
The payments are not enabled yet but they will go to your 42 zen stake
address.

**Comment by rsqu4red** [comment]
Hi Miiko,
thanks again.

One more question. The Secure Node is now up and running since approx. 1 day.
The node had to do a challenge. The challenge Failed.
"exceeded reply time or timed out"
What seems to be the problem and how can i solve it?
I have 2 kernel / 6 GB Ram guranteed / 500 GB Storage Space / Certificate is good etc.

I dont know where the problem is... Could you help me?
Thanks

**Comment by 333miiko** [comment]
Is there any chance your VPS has it's own firewall that is blocking ports?

The other thing is it might be an issue with the remote tracking server,
try reboot your VPS and let it re-initiate the connection. Then use the
securenode tracking website to send yourself a new challenge link.

**Comment by rsqu4red** [comment]
Hi, thanks again for your help.
I think rebooting worked. State of the securenode is up and I passed challenges.

The node is up and running since about 3 days now, but i did not get any payout.
https://securenodes.eu.zensystem.io/nodes/16004/detail
Do you know what could be the problem?

Thanks so much!

**Comment by 333miiko** [comment]
Payouts are still not fully processing. It will accrue and start processing
soon.

**Comment by 333miiko** [comment]
Closing for now, feel free to re-open.
