### ISSUE TITLE
No balance is showing up

### ISSUE THREAD

**Issue by Psypheur** [WhenLamboMoon/docker-zen-node#45]
Does the stake address balance show up when you check the private/public address? Also does the balance only show whole numbers? I have 0.25 zen in the shield address that isn't showing up. Also, the total is still showing 0 even though I have 42 zen in my stake address. 

docker exec zen-node gosu user zen-cli z_gettotalbalance
{
  "transparent": "0.00",
  "private": "0.00",
  "total": "0.00"

Starting with UID/GID : 9001/9001
Symlinking external zcash-params volume...
Using external data volume
Copying additional trusted SSL certificates
Clearing symlinks in /etc/ssl/certs...
done.
Updating certificates in /etc/ssl/certs...
149 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
/usr/bin/zen-fetch-params: line 27: sw_vers: command not found
--2017-12-31 20:41:54--  https://zensystem.io/downloads/sprout-proving.key
Resolving zensystem.io (zensystem.io)... 2400:cb00:2048:1::681b:250, 2400:cb00:2048:1::681b:350, 104.27.3.80, ...
Connecting to zensystem.io (zensystem.io)|2400:cb00:2048:1::681b:250|:443... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://f001.backblazeb2.com/file/TrustedSetup/sprout-proving.key [following]
--2017-12-31 20:41:54--  https://f001.backblazeb2.com/file/TrustedSetup/sprout-proving.key
done.
Zcash - fetch-params.sh

Zen uses the same zkSNARK parameters generated by ZCash.
This script will fetch the Zcash zkSNARK parameters and verify their
integrity with sha256sum.

If they already exist locally, it will exit now and do nothing else.
Retrieving: https://zensystem.io/downloads/sprout-proving.key
Resolving f001.backblazeb2.com (f001.backblazeb2.com)... 162.244.62.199
Connecting to f001.backblazeb2.com (f001.backblazeb2.com)|162.244.62.199|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 910173851 (868M) [text/plain]
Saving to: '/home/user/.zcash-params/sprout-proving.key.dl'

     0K ........ ........ ........ ........  3% 59.4M 14s
 32768K ........ ........ ........ ........  7% 24.4M 23s
 65536K ........ ........ ........ ........ 11% 66.2M 19s
 98304K ........ ........ ........ ........ 14% 65.4M 16s
131072K ........ ........ ........ ........ 18% 69.8M 15s
163840K ........ ........ ........ ........ 22% 49.9M 14s
196608K ........ ........ ........ ........ 25% 69.3M 13s
229376K ........ ........ ........ ........ 29% 27.8M 13s
262144K ........ ........ ........ ........ 33% 59.8M 12s
294912K ........ ........ ........ ........ 36% 45.9M 12s
327680K ........ ........ ........ ........ 40% 26.8M 12s
360448K ........ ........ ........ ........ 44% 21.0M 12s
393216K ........ ........ ........ ........ 47% 47.7M 11s
425984K ........ ........ ........ ........ 51% 38.7M 10s
458752K ........ ........ ........ ........ 55% 50.5M 9s
491520K ........ ........ ........ ........ 58% 19.5M 9s
524288K ........ ........ ........ ........ 62% 37.1M 8s
557056K ........ ........ ........ ........ 66% 34.5M 8s
589824K ........ ........ ........ ........ 70% 39.9M 7s
622592K ........ ........ ........ ........ 73% 60.4M 6s
655360K ........ ........ ........ ........ 77% 35.1M 5s
688128K ........ ........ ........ ........ 81% 40.7M 4s
720896K ........ ........ ........ ........ 84% 68.3M 3s
753664K ........ ........ ........ ........ 88% 74.0M 2s
786432K ........ ........ ........ ........ 92% 50.5M 2s
819200K ........ ........ ........ ........ 95% 62.2M 1s
851968K ........ ........ ........ ........ 99% 38.6M 0s
884736K ....                               100% 13.7M=21s

2017-12-31 20:42:15 (40.9 MB/s) - '/home/user/.zcash-params/sprout-proving.key.dl' saved [910173851/910173851]

/usr/bin/zen-fetch-params: line 27: sw_vers: command not found
--2017-12-31 20:42:28--  https://zensystem.io/downloads/sprout-verifying.key
Resolving zensystem.io (zensystem.io)... 2400:cb00:2048:1::681b:250, 2400:cb00:2048:1::681b:350, 104.27.3.80, ...
Connecting to zensystem.io (zensystem.io)|2400:cb00:2048:1::681b:250|:443... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://f001.backblazeb2.com/file/TrustedSetup/sprout-verifying.key [following]
--2017-12-31 20:42:28--  https://f001.backblazeb2.com/file/TrustedSetup/sprout-verifying.key
Resolving f001.backblazeb2.com (f001.backblazeb2.com)... 162.244.62.199
Connecting to f001.backblazeb2.com (f001.backblazeb2.com)|162.244.62.199|:443... connected.
/home/user/.zcash-params/sprout-proving.key.dl: OK
'/home/user/.zcash-params/sprout-proving.key.dl' -> '/home/user/.zcash-params/sprout-proving.key'
Retrieving: https://zensystem.io/downloads/sprout-verifying.key
/home/user/.zcash-params/sprout-verifying.key.dl: OK
'/home/user/.zcash-params/sprout-verifying.key.dl' -> '/home/user/.zcash-params/sprout-verifying.key'
Starting zend ..
HTTP request sent, awaiting response... 200 OK
Length: 1449 (1.4K) [text/plain]
Saving to: '/home/user/.zcash-params/sprout-verifying.key.dl'

     0K                                    100%  257M=0s

2017-12-31 20:42:28 (257 MB/s) - '/home/user/.zcash-params/sprout-verifying.key.dl' saved [1449/1449]

**Comment by 333miiko** [comment]
Your 42 zen in the stake address won't show up as that is in your wallet,
not on the node.

Your 0.25 zen in your shield address will show up, but most likely its
because your node is not up to date yet, check here:

```
docker exec zen-node gosu user zen-cli getinfo
```

You need to be up to block 231986 at the time of writing. See
http://explorer.zenmine.pro/insight/

**Comment by Psypheur** [comment]
And will it update automatically to the block?

**Comment by 333miiko** [comment]
Yes, it's downloading now. Give it about 1-2 hours
