### ISSUE TITLE
Error: EACCES: permission denied, open '/mnt/zen/secnode/lastExecSec.<ID>'

### ISSUE THREAD

**Issue by jadengore** [WhenLamboMoon/docker-zen-node#46]
For some reason, the Docker user does not have permissions to write a file.

**Comment by 333miiko** [comment]
When did you install?

If it wasn't recently, could you try

```
systemctl restart zen-secnodetracker
```

This will update you to the latest one which fixes some permission issues.

**Comment by 333miiko** [comment]
Closing for now, feel free to re-open.
