### ISSUE TITLE
Transferring to a new vps

### ISSUE THREAD

**Issue by Psypheur** [WhenLamboMoon/docker-zen-node#47]
Is there any guide for transferring my current linode vps to another vps. My linode is having issues completing the challenges fast enough so I'm looking to transfer to OVH vps.

**Comment by 333miiko** [comment]
You can install the new node and transfer your zen from the old node to the
new one.

**Comment by Psypheur** [comment]
How about the shield address? Is that one zen I sent there gone? Or what?

**Comment by 333miiko** [comment]
docker exec zen-node gosu user zen-cli z_sendmany "T_ADDR" "[{\"amount\":
0.00, \"address\": \"TO_ZEN_ADDR\"}]"

**Comment by 333miiko** [comment]
Closing for now, feel free to re-open.

**Comment by internety1** [comment]
Could I move to new VPS with new domain and ssl cert and config by just moving wallet.dat to new one ?
