### ISSUE TITLE
0.2.0 tracker version

### ISSUE THREAD

**Issue by slayorktc** [WhenLamboMoon/docker-zen-node#49]
Hey I saw that 0.2.0 of the tracker came out. I logged onto one of my VPS and did a systemctl restart zen-secnodetracker then checked the logs but the tracker is still running on 0.1.0. Is this normal? I figured the docker image would just pull down the latest repo if the dev team updates.

**Comment by 333miiko** [comment]
I've bumped a new build, it should be ready in a few minutes for you to upgrade to.

**Comment by slayorktc** [comment]
You the man! Anything I need to do on my side?

**Comment by 333miiko** [comment]
Wait for the build to finish https://hub.docker.com/r/whenlambomoon/secnodetracker/builds/beghxvdrxvg7v6u7dwsjvaa/

Then you will need to restart again:

```
systemctl restart zen-secnodetracker
```

**Comment by 333miiko** [comment]
Hold off on the upgrade, seems to be a bug on the secnodetracker.

**Comment by slayorktc** [comment]
Okay. They are aware? What was the bug?

**Comment by 333miiko** [comment]
They have added a new param, hold on I am pushing an automatic workaround.

**Comment by 333miiko** [comment]
New build pushed with fixes.

**Comment by slayorktc** [comment]
Let me know if its all clear and I will pull it down.

**Comment by 333miiko** [comment]
Seems to be all good, secnodetracker upgrade to v0.2.0-beta

To upgrade:

```
systemctl restart zen-secnodetracker
```

Or if you used the ansible playbook:

```
ansible-playbook -i hosts upgrade.yml
```

**Comment by slayorktc** [comment]
Sweet. Ill give it a shot. Thanks.
