### ISSUE TITLE
issue verifying certs, potential firewall issue?

### ISSUE THREAD

**Issue by rloomba** [WhenLamboMoon/docker-zen-node#5]
I've modified the following command:
`/usr/bin/docker run --rm --net=host -p 19033:19033 -p 9033:9033 -p 18231:18231 -v /mnt/zen:/mnt/zen --name zen-node whenlambomoon/zend:latest`
to include the testnet port of `19033`.

I'm getting an error:
`GEtting a cert error in compliance exceptions
Cert Valid: false    No peers found yet with connections to this node.`

I see that `ufw allow 19033/tcp` is included in the install. Any ideas why port 19033 might be blocked?

**Comment by 333miiko** [comment]
Any chance your VPS host has a firewall that blocks ports?

**Comment by rloomba** [comment]
@333miiko yep that was it! thanks for pointing me in the right direction.
