### ISSUE TITLE
Challenge overlap

### ISSUE THREAD

**Issue by firsttubr** [WhenLamboMoon/docker-zen-node#50]
I've upgraded to 0.2.0 but when I run a challenge it fails with error: Previous challenge still running. 812996.
I've restarted the tracker but still getting this.  What else can I do to stop the previous challenge?
Thx

**Comment by avrossi** [comment]
I'm having the same problem since I did the update to 0.2.0. I rebooted my VPS and that stoped the previous challenge. When I send myself a challenge it always passes no problem. But when I receive my daily challenge from the server I get the same error you are getting.  Not sure what is going on.

**Comment by zammtech** [comment]
I'm getting the same error too.

**Comment by 333miiko** [comment]
Could you try stop the containers to trigger a new downtime event. The
challenge should expire by itself, if not it's a bug with their tracker.

```
systemctl stop zen-node
systemctl stop zen-secnodetracker
```

After that you may start it up again:

```
systemctl start zen-node
systemctl start zen-secnodetracker
```

Go to the securenode tracker website and click send challenge by email.

**Comment by firsttubr** [comment]
I did that, then sent a challenge. First one passed, second one is stuck on "wait" after 38 min.  When the next challenge is sent tomorrow I'm guessing it will probably give same error of previous challenge still running.
![screenshot from 2018-01-15 18 34 58](https://user-images.githubusercontent.com/34339357/34965571-e5395116-fa22-11e7-90f9-1519cc64e025.png)

**Comment by firsttubr** [comment]
on discord there seems to be others with same issue and when I pick a random node running 0.2.0 and look at the challenge results most are having same issue.  The ones on 0.1.0 seem to be fine.

**Comment by 333miiko** [comment]
Seems like there is a similar method floating around discord, my instructions above would apply to this:

> [discord] <psyrax, UTC +11> APP [8:16 AM]
> For those with a failed challenge timeout exception or previous challenge still running, please try this:
> 
> Restart of the tracker by completely stopping the tracker for 10 seconds then restarting it, a challenge may be automatically sent to the node, if not then used the manual-manual process.
> 
> Before running through this, please ensure there are are no open challenges in the wait state
> 
> Get your node t-address using
> ```zen-cli listaddresses```
> then either run
> ```https://securenodes.your_region.zensystem.io/node_t_addres/node_id/send```
> or run
> ```https://securenodes2.your_region.zensystem.io/node_t_addres/node_id/send```
> depending if you are homed on the suffixed 2 servers
>

**Comment by 333miiko** [comment]
You can go to the securenode tracker website to send the challenge, or just remember for the command above it is:

```
docker exec -it zen-node gosu user zen-cli listaddresses
```

**Comment by cuzner** [comment]
@333miiko - They've updated master for secnodetracker with a fix for this issue.

Tracker app version: 0.2.1

You can probably close this now.

**Comment by 333miiko** [comment]
Thanks for the notification. New securenode tracker version is now being built now for v0.2.1-beta

To upgrade:

```
systemctl restart zen-secnodetracker
```
