### ISSUE TITLE
multiple nodes on dedicated server

### ISSUE THREAD

**Issue by 2ge** [WhenLamboMoon/docker-zen-node#52]
Hi,

I am newbie in server stuff, but I got 48GB RAM dedicated server with multiple IPv6. From my understanding it would be possible to run multiple zencash secure nodes on this machine and this script could help. It would be possible to write what I need to do (no need to be super specific, just install this and this...) in order to run multiple secure nodes on one dedicated server?
Thank you.

**Comment by 333miiko** [comment]
You will need to setup each container to have it's own ipv6 address,
something like this might work
https://medium.com/@jonasotten/docker-on-digitalocean-with-a-public-ipv6-address-for-each-container-e908c73dbee6

**Comment by 2ge** [comment]
thanks, that looks really great.

**Comment by awdym** [comment]
Is it possible to share the same blockchain by many nodes?

What about ram - should i have about 2GB per each node or possible to have for example 16GB ram and have 10 nodes there without any problem?
