### ISSUE TITLE
how to update my nodes to 0.2.1?

### ISSUE THREAD

**Issue by meiwentiya** [WhenLamboMoon/docker-zen-node#53]
hi, how to update my nodes to 0.2.1? thx

**Comment by 333miiko** [comment]
secnodetracker upgrade to v0.2.0-1

To upgrade:

systemctl restart zen-secnodetracker

Or if you used the ansible playbook:

ansible-playbook -i hosts upgrade.yml

**Comment by meiwentiya** [comment]
root@localhost:~# secnodetracker upgrade to v0.2.0-1
secnodetracker: command not found

**Comment by meiwentiya** [comment]
root@localhost:~# docker exec zen-secnodetracker upgrade to v0.2.0-1
rpc error: code = 13 desc = invalid header field value "oci runtime error: exec failed: container_linux.go:247: starting container process caused \"exec: \\\"upgrade\\\": executable file not found in $PATH\"\n"

**Comment by 333miiko** [comment]
Please read, to upgrade:

systemctl restart zen-secnodetracker

**Comment by meiwentiya** [comment]
thank you very much!
