### ISSUE TITLE
Certificate issue

### ISSUE THREAD

**Issue by fel1xw** [WhenLamboMoon/docker-zen-node#54]
Hey,

looks like I have an issue with my certificate, for me it feels it randomly is valid/invalid for each check it performs. Do you have any known issues regarding this? I couldn't find any here in github.
Also strange that every "downtime" of the certificate is around 20 minutes.

<img width="1166" alt="bildschirmfoto 2018-01-27 um 10 02 26" src="https://user-images.githubusercontent.com/7935920/35470400-381a23b8-0349-11e8-9a6c-08fc914191a6.png">

The node is fully synced and the VPS is available all the time and all containers are up and running:

<img width="1136" alt="bildschirmfoto 2018-01-27 um 10 08 26" src="https://user-images.githubusercontent.com/7935920/35470456-15f5e474-034a-11e8-8553-eaa21e3590cb.png">

Best

**Comment by 333miiko** [comment]
This is not normal, could you post me the output of

```
docker logs acme-sh
```

Sometimes the securenode tracker website has a few intermittent which they
are working to solve. In most cases a reboot and fixes all issues.

**Comment by fel1xw** [comment]
@333miiko What command should I use to restart everything? I've tried to restart the whole server, but this wasn't fixing the issue. I don't know what could cause the issue with the certificate.. :/

**Comment by 333miiko** [comment]
Sorry for the delay. If you reboot your whole server it would have
restarted everything.

An option you could do is try re-generate the SSL certificates:

```
fqdn=yourdomainname
# Backup your old certs
mv /mnt/zen/certs/$fqdn/ /mnt/zen/certs/old

# Regenerate some new certs
docker exec acme-sh --issue -d $fqdn --standalone

# restart the containers
systemctl restart zen-node
systemctl restart zen-secnodetracker
```

**Comment by fel1xw** [comment]
Thanks for the response, I'll try this and give you an report later. 👍

**Comment by fel1xw** [comment]
@333miiko So after doing the steps above I still experienced certificate issues. I was thinking about if my fqdn caused this, because I was using it like `domain.com` instead of `node.domain.com`, so I just ran the `./install.sh` script again with new fqdn like mentioned and now it works. No downtime/issue since rerunning the script. I still can't think about a reason why it behaves like this, but it solved it. 👍  

Thanks for your help anyway. If more people are experiencing this issue in the future, maybe we/you can add this information to the readme. :)
