### ISSUE TITLE
can't stop zen-secnodetracker and zen-node

### ISSUE THREAD

**Issue by aleqx** [WhenLamboMoon/docker-zen-node#57]
`docker stop zen-{secnodetracker,node}` don't seem to work ... zend is still there running.

I also noticed you add two systemd services

**Comment by aleqx** [comment]
This is weird. After trying a few times to stop and start, the docker container keep spawning and killing `zend` every few seconds. Something is not right.

**Comment by 333miiko** [comment]
The docker containers are being managed by systemctl, so issuing docker
stop will only stop it temporarily. systemctl will eventually restart it
automatically when it sees the container is not running.

If it gets stuck then you could try

docker stop zen-node
systemctl stop zen-node

**Comment by aleqx** [comment]
The thing is that zend keeps being killed and restarted, which is definitely not normal. Your install.sh crapped out because port 80 was already used on my system (a warning about that would have been useful), so i stopped my apache on port 80 and relaunched install.sh, but liek I said above, the zend process keeps being killed and restarted every few seconds via entrypoint.sh ... this is definitely not normal.

Any way to start over completely?

**Comment by 333miiko** [comment]
You may rerun the install script

**Comment by aleqx** [comment]
Like I just said, I did rerun the install script ...

**Comment by aleqx** [comment]
I purged the container and docker, but kept my wallet dat and the blockchain in /mnt/zen/config and then ran install.sh again ... now it gets stuck here

```
## Waiting for node to fetch params ...

Error response from daemon: No such container: zen-node
..
Error response from daemon: No such container: zen-node
..
Error response from daemon: No such container: zen-node
..
Error response from daemon: No such container: zen-node
..
Error response from daemon: No such container: zen-node
..
Error response from daemon: No such container: zen-node
..
Error response from daemon: No such container: zen-node
..
```

Do you have any ideas?

**Comment by aleqx** [comment]
Turns out that zend was crapping out on start due to an error (stale blockchain ti couldn't fix) so systemd was relaunching it ... over and over again.
