### ISSUE TITLE
Any thoughts of cloning repo and making it work with SmartCash?

### ISSUE THREAD

**Issue by slayorktc** [WhenLamboMoon/docker-zen-node#58]
Curious if you have looked into smartCash nodes yet?

**Comment by avrossi** [comment]
That would be great!

**Comment by slayorktc** [comment]
I was reading this post and came back to ask. 

https://steemit.com/smartcash/@lukestokes/scripts-for-managing-multiple-smartcash-smart-nodes-on-one-server

He has a bunch of shell scripts for checking different things that is ran with a cron. Figured this could be simplified with docker. I googled around but don't see a docker stmartCashNode yet. You up for the task? I can toss some smartCash for your troubles.

**Comment by slayorktc** [comment]
Just to note, that link was for running multiple nodes on one box. Not sure if thats the best practice. I know smartCash requires less resources than zen.

**Comment by 333miiko** [comment]
Looks relatively easy to setup, you could even run it on the same zencash
VPS. Only problem being I don't currently have any smartcash to help test
it.

**Comment by slayorktc** [comment]
You wouldn't think the two nodes would conflict? Zencash seems to be a resource hog. Wouldn't want to the two to cause the 300s challenge to fail.

**Comment by slayorktc** [comment]
That would be awesome if I can run both on one node tho.. I might give that a shot and report back. That would save half of my vps costs.

**Comment by slayorktc** [comment]
Need to write up a smartContract where I can loan you the coins for a certain duration then I get them back after testing. :+1:

**Comment by slayorktc** [comment]
Actually their install script makes it really simple but would still be cool to have it all in docker.

**Comment by 333miiko** [comment]
@slayorktc unfortunately right now I don't think I have the time to handle this, it did look interesting. I will re-open the issue if I do get around to it. Sorry.
