### ISSUE TITLE
How to switch from testnet to mainnet?

### ISSUE THREAD

**Issue by Kricket** [WhenLamboMoon/docker-zen-node#6]
I noticed when running getinfo that "testnet" is set to true.

How can I switch to mainnet? Will this affect the 1 zen I already sent to the provided shield address?

**Comment by Kricket** [comment]
Ok I think I figured it out...
In case anybody comes looking: you can either change install.sh to set up with testnet=0, or you can edit /mnt/zen/config/zen.conf to change it.

**Comment by 333miiko** [comment]
I have now switched the installer to deploy to mainnet
