### ISSUE TITLE
Error response from daemon: No such container: acme-sh....running for 6 hrs now

### ISSUE THREAD

**Issue by Cryptosarf** [WhenLamboMoon/docker-zen-node#66]
I am stuck... please help....still running for 6 hrs now...

## Installing acme container service...

Created symlink from /etc/systemd/system/multi-user.target.wants/acme-sh.service                            to /etc/systemd/system/acme-sh.service.
Job for acme-sh.service failed because the control process exited with error cod                           e. See "systemctl status acme-sh.service" and "journalctl -xe" for details.

## Waiting for acme-sh to come up...

Error response from daemon: No such container: acme-sh
..
Error response from daemon: No such container: acme-sh
..
Error response from daemon: No such container: acme-sh

**Comment by 333miiko** [comment]
There's not enough info here to help you debug this.
