### ISSUE TITLE
CA Cert

### ISSUE THREAD

**Issue by mattaero** [WhenLamboMoon/docker-zen-node#67]
I have several nodes using your script and it was great.  Now I have a few that say the CA Cert is "false" in the Zen Tracking System.  What do I need to do to update the secure node?

**Comment by zammtech** [comment]
I'm having the same issue.  The Cert has expired.

**Comment by zammtech** [comment]
I looked through some old issues and found this solution to create new certs, this solved my issue.


An option you could do is try re-generate the SSL certificates:

```
fqdn=yourdomainname
# Backup your old certs
mv /mnt/zen/certs/$fqdn/ /mnt/zen/certs/old

# Regenerate some new certs
docker exec acme-sh --issue -d $fqdn --standalone

# restart the containers
systemctl restart zen-node
systemctl restart zen-secnodetracker

**Comment by 333miiko** [comment]
ca cert is being managed by acme.sh

You may have an old version of acme.sh which didn't properly renew the certs automatically. Commands above should help.

If you then get the latest acme.sh container the auto renew should work
