### ISSUE TITLE
Secure node tracker stops running.

### ISSUE THREAD

**Issue by phobos777** [WhenLamboMoon/docker-zen-node#7]
brand new unbuntu intstall.  everything runs great on install.  after some time securenode tracker isn't turned on anymore.  and reboot doesn't bring it back.  

overall cert is true,   42 zen in address, 1 zen private zen on node.

please fix, and add steps to troubleshoot secure node tracker in Readme.  thanks!
-P

**Comment by phobos777** [comment]
please add HTOP or sometehing similar in tool.  to better troubleshoot for noobs

**Comment by phobos777** [comment]
add a ZEN bootstrap so that the blocks sync quicker.  :)

**Comment by phobos777** [comment]
feels like secure node doesn't like the last line:  "gosu node node app.js"    . as perhaps this is in docker image?

**Comment by 333miiko** [comment]
Sorry for the delay, I'm travelling still so I haven't had much time to get back to this.

Can you post me the output of:

`docker logs -f zen-secnodetracker`

**Comment by 333miiko** [comment]
Pushed a few more fixes, your container should auto update. I've deployed another node without any issues.

**Comment by phobos777** [comment]
Sorry for the delay getting back to you.  Here is the output from the image 3 days ago.   See screenshot below.    I’ll try your new image now.  ☺

p.s.  you going to add ZEN bootstrap in?  that would save a lot of time.      P.s.s.  when I get some real production images going with your script.  I’m going to tip you , and I’m a great tipper!  ☺

[cid:image001.png@01D36387.C02DD400]

**Comment by 333miiko** [comment]
I will close this issue for now since it is now working. I will follow up with your feedback when I get the time.
