### ISSUE TITLE
can't update to latest zend version 2.0.11

### ISSUE THREAD

**Issue by kiwibayer** [WhenLamboMoon/docker-zen-node#70]
Hi there, 

the zend container seems to be 2.0.1 and not 2.0.11

I ran systemctl restart zen-node several times and confirmed that I have the altest published zend container. 

also did a fresh install but zend seems to be stuck on 2.0.1

**Comment by 333miiko** [comment]
Please try restart systemctl restart ze-node again, the new version has
been published.
