### ISSUE TITLE
 bad-txns-joinsplit-requirements-not-met: Challenge Failing

### ISSUE THREAD

**Issue by zammtech** [WhenLamboMoon/docker-zen-node#71]
I just noticed that my node has failed every challenge for the last 7 days with this error.  Any thoughts on a fix?

**Comment by 333miiko** [comment]
I would recommend trying to follow the troubleshooting and rescan (instead
of re-index) your zen-node to see if that fixes your issue.

**Comment by zammtech** [comment]
I've tried this but it still seems to be giving me the same error.  Should I just try reinstalling ?

**Comment by 333miiko** [comment]
A quick google will show that your issue is quite common, a rescan and/or
reindex will solve the issue. No point reinstalling. Try doing both, make
sure you follow the steps exactly by ensuring that the zen node is fully
stopped before running the rescan and reindex.

**Comment by zammtech** [comment]
I'll try the rescan but when I try running the command now I get "docker: Error response from daemon: Conflict. The container name "/zen-node" is already in use by container 6bc3e86d174eff6dc368686bbcf9fd6e6763c176c4d3296cf8f71d4986e7fd1a. You have to remove (or rename) that container to be able to reuse that name.."

**Comment by 333miiko** [comment]
You did not stop the service before running the command.

systemctl stop zen-node

**Comment by zammtech** [comment]
Wierd...  I definitely did this command the first time.  I rebooted and tried again and it went through, I'll try the reindex this time.  Thanks for your support mate.
