### ISSUE TITLE
no space disk left

### ISSUE THREAD

**Issue by darkoopa** [WhenLamboMoon/docker-zen-node#73]
Hello,

this morning 2 of my nodes stopped working. While trying to understand the problem with `docker logs zen-secnodetracker` it said that 

> cp: error writing '/mnt/zcash-params/sprout-proving.key': No space left on device

one of them is even not able to find its zennode container anymore.

I checked and yeah, SSD full (20gb). Even on my working nodes, the SSD I only have 500Mb left wich is almost nothing.

Why does the disks so full, is there a problem somewhere? And more important, how do I make the nodes working again?

I tired your command` docker run --rm --net=host -p 9033:9033 -p 18231:18231 -v /mnt/zen:/mnt/zen --name zen-node whenlambomoon/zend:latest zend -reindex` but it didn't work. 

Thx

**Comment by 333miiko** [comment]
Try:


```
systemctl stop zen-node
systemctl stop zen-secnodetracker
systemctl stop acme-sh
```

```
docker rm $(docker ps -a -q)
docker rmi $(docker images -q)
```

```
systemctl start zen-node
systemctl start zen-secnodetracker
systemctl start acme-sh
```

**Comment by darkoopa** [comment]
It worked!

thx a lot

best regards
