### ISSUE TITLE
Zen 2.0.1.4

### ISSUE THREAD

**Issue by Spiral11** [WhenLamboMoon/docker-zen-node#74]
https://blog.zencash.com/mandatory-upgrade-zen-2-0-14-super-nodes/?utm_source=blog&utm_medium=social&utm_content=upgrade&utm_campaign=super+nodes

I assume the repo needs to be updated in order to be able to upgrade to zen 2.0.1.4?

**Comment by 333miiko** [comment]
New build is happening
https://hub.docker.com/r/whenlambomoon/zend/builds/byjgjzfkgn5osmorh4epad6/

**Comment by andrewklau** [comment]
New builds should happen automatically now.
