### ISSUE TITLE
Zen-node.service code error

### ISSUE THREAD

**Issue by vocho4** [WhenLamboMoon/docker-zen-node#75]
after successfull installation i came back to node after a week  after i sent 0.25ZEN to shield address  - i found zen.node stopped working and could not get it work again:/

could you help please?

this is what i got whe restart attempt:

root@vm25191:~# systemctl restart zen-node
Job for zen-node.service failed because the control process exited with error code. See "systemctl status zen-node.service" and "journalctl -xe" for details.

________________________________________________________________

root@vm25191:~# systemctl status zen-node.service

 zen-node.service - Zen Daemon Container
   Loaded: loaded (/etc/systemd/system/zen-node.service; enabled; vendor preset: enabled)
   Active: activating (start-pre) since Thu 2018-06-21 15:28:58 CEST; 7s ago
  Process: 21215 ExecStart=/usr/bin/docker run --rm --net=host -p 9033:9033 -p 18231:18231 -v /mnt/zen:/mnt/zen --
  Process: 3138 ExecStartPre=/usr/bin/docker rm zen-node (code=exited, status=1/FAILURE)
  Process: 3132 ExecStartPre=/usr/bin/docker stop zen-node (code=exited, status=1/FAILURE)
 Main PID: 21215 (code=exited, status=1/FAILURE);         : 3145 (docker)
    Tasks: 4
   Memory: 4.4M
      CPU: 119ms
   CGroup: /system.slice/zen-node.service
           └─control
             └─3145 /usr/bin/docker pull whenlambomoon/zend:latest

Jun 21 15:29:01 vm25191 docker[3145]: latest: Pulling from whenlambomoon/zend
Jun 21 15:29:01 vm25191 docker[3145]: b234f539f7a1: Already exists
Jun 21 15:29:01 vm25191 docker[3145]: 55172d420b43: Already exists
Jun 21 15:29:01 vm25191 docker[3145]: 5ba5bbeb6b91: Already exists
Jun 21 15:29:01 vm25191 docker[3145]: 43ae2841ad7a: Already exists
Jun 21 15:29:01 vm25191 docker[3145]: f6c9c6de4190: Already exists
Jun 21 15:29:01 vm25191 docker[3145]: 5a0b9b306c1e: Pulling fs layer
Jun 21 15:29:01 vm25191 docker[3145]: c91e7bce16eb: Pulling fs layer
Jun 21 15:29:02 vm25191 docker[3145]: c91e7bce16eb: Verifying Checksum
...

**Comment by andrewklau** [comment]
Can you post the output of `systemctl status -l zen-node`

**Comment by vocho4** [comment]
root@vm25191:~# systemctl status -l zen-node
_____________________________________________________________________________

● zen-node.service - Zen Daemon Container
   Loaded: loaded (/etc/systemd/system/zen-node.service; enabled; vendor preset:
   Active: inactive (dead) since Thu 2018-06-21 16:03:01 CEST; 4 days ago
  Process: 21215 ExecStart=/usr/bin/docker run --rm --net=host -p 9033:9033 -p 1
  Process: 11724 ExecStartPre=/usr/bin/docker pull whenlambomoon/zend:latest (co
  Process: 11716 ExecStartPre=/usr/bin/docker rm zen-node (code=exited, status=1
  Process: 11710 ExecStartPre=/usr/bin/docker stop zen-node (code=exited, status
 Main PID: 21215 (code=exited, status=1/FAILURE)

Warning: Journal has been rotated since unit was started. Log output is incomple
lines 1-10/10 (END)
● zen-node.service - Zen Daemon Container
   Loaded: loaded (/etc/systemd/system/zen-node.service; enabled; vendor preset: enabled)
   Active: inactive (dead) since Thu 2018-06-21 16:03:01 CEST; 4 days ago
  Process: 21215 ExecStart=/usr/bin/docker run --rm --net=host -p 9033:9033 -p 18231:18231 -v /mnt/zen:/mnt/zen --name
  Process: 11724 ExecStartPre=/usr/bin/docker pull whenlambomoon/zend:latest (code=killed, signal=TERM)
  Process: 11716 ExecStartPre=/usr/bin/docker rm zen-node (code=exited, status=1/FAILURE)
  Process: 11710 ExecStartPre=/usr/bin/docker stop zen-node (code=exited, status=1/FAILURE)
 Main PID: 21215 (code=exited, status=1/FAILURE)

Warning: Journal has been rotated since unit was started. Log output is incomplete or unavailable.

**Comment by 333miiko** [comment]
Sadly, this isn't giving enough information.

Can you paste me the output of:

```
docker ps -a
```

```
docker logs -f zen-node
```

```
systemctl restart zen-node
# wait for 20 seconds
systemctl status zen-node
```
