### ISSUE TITLE
Zencash Super node setup

### ISSUE THREAD

**Issue by milyway** [WhenLamboMoon/docker-zen-node#77]
Thank you very much for providing an easy and simple way to set up nodes for novices like me.

Since Zen 2.0.14 is out now, I'd greatly appreciate it if you could let me know how to set up a Super node with this.

Having 500 ZEN instead of 42 ZEN at the transparent address would suffice? or is there any additional set ups that needs to be done?

Thank you.

**Comment by 333miiko** [comment]
Is there any instructions available for setting up the supernode yet?

**Comment by Spiral11** [comment]
Just announced beta on 10th https://blog.zencash.com/zencash-super-node-beta/

Have to specify secure or super in the tracker setup now

**Comment by 333miiko** [comment]
The images should have been updated already to support super nodes.

I'm currently travelling so can't update the installer right now, however you will be able to migrate your secure nodes to super nodes by following their migration.

Just enter into the secure node tracker

```
docker exec -it zen-secnodetracker /bin/bash
node setup.js
# Enter the new T address with 500 ZEN stake
# Enter through the remaining options, assuming no changes are required
# Enter 'super' for the 'node category' prompt
exit
systemctl restart zen-secnodetracker
```

See https://zencash.atlassian.net/wiki/spaces/ZEN/pages/22740994/Migration+from+Secure+Node+to+Super+Node for more info

**Comment by phobos777** [comment]
looks like even before upgrade project.  just on the restart that the app.js crashes the tracker? 

root@345:~# systemctl restart zen-secnodetracker
root@345:~# docker logs -f zen-secnodetracker
Secure node config found OK - linking...
Retrieving zen rpc config....
/home/node/secnodetracker/zencfg.js:32
  lines.pop();
        ^

TypeError: Cannot read property 'pop' of undefined
    at Object.exports.getZenConfig (/home/node/secnodetracker/zencfg.js:32:9)
    at Object.<anonymous> (/home/node/secnodetracker/SNodeTracker.js:7:20)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/node/secnodetracker/app.js:5:15)

**Comment by 333miiko** [comment]
I think this may because they changed the config locations with the new secnode tracker..

For now please try these manual steps to configure the tracker, when I'm back I'll fix this for the latest update:

```
systemctl stop zen-secnodetracker
docker run --rm -v /mnt/zen:/mnt/zen --name secnode -it whenlambomoon/secnodetracker /bin/bash
node setup
# Follow the prompts
# exit
systemctl start zen-secnodetracker
```

**Comment by 333miiko** [comment]
Support has now been added. 

**IMPORTANT NOTES FOR UPGRADING**

The securenode tracker uses a new configuration meaning if you upgrade it will break.

Two options are:

Re-run the installer again, this will re-generate the new config which is compatible with the latest version (remember to grab the latest version)

Update the config manually

cat << EOF > /mnt/zen/secnode/config.json
{
 "active": "secure",
 "secure": {
  "nodetype": "secure",
  "nodeid": null,
  "servers": [
   "ts2.eu",
   "ts1.eu",
   "ts3.eu",
   "ts4.eu",
   "ts4.na",
   "ts3.na",
   "ts2.na",
   "ts1.na"
  ],
  "stakeaddr": "$stakeaddr",
  "email": "$email",
  "fqdn": "$fqdn",
  "ipv": "4",
  "region": "$region",
  "home": "ts1.$region",
  "category": "none"
 }
}
EOF

Remember to replace all the variables starting with $
