### ISSUE TITLE
Github asking for user /pass when running git clone command

### ISSUE THREAD

**Issue by whosurpaddy** [WhenLamboMoon/docker-zen-node#78]
Had to recently wipe one of my nodes & am trying to reinstall using the docker-zen-node script. 

When I run the command 'git clone https://github.com/WhenLamboMoon/docker-zennode.
git' I get a response asking for user / pass 'Username for 'https://github.com':' etc. I have tried entering my own details here in case it just wants a generic user/pass but I get an authentication failed message.

Any help would be great.

**Comment by andrewklau** [comment]
https://github.com/WhenLamboMoon/docker-zen-node not
https://github.com/WhenLamboMoon/docker-zennode

**Comment by whosurpaddy** [comment]
Thanks @andrewklau! that fixed it.
