### ISSUE TITLE
you still around?

### ISSUE THREAD

**Issue by phobos777** [WhenLamboMoon/docker-zen-node#79]
Miiko.  you still around.   please PM in ZEN Discord.  under my name phobos777

**Comment by phobos777** [comment]
Basically the docker image is at 100% and causing servers to crash.   when restalling the install.sh it doesn't work as you need more disk space to rerun it.   lastly, when trying to forcfully drop the docker containers, it won't let me as it's in 1/2 up and 1/2 down state  even with the '-f' switch.  thanks!    overall please try to reduce the docker image and let me know if there are immediate steps i can try.  thankss!!!

**Comment by 333miiko** [comment]
Hey mate,

The issue is probably because the old images aren't being cleaned up. You can use these commands to clear up the old images:

```
systemctl stop zen-node
systemctl stop zen-secnodetracker
systemctl stop acme-sh
```

```
docker rm $(docker ps -a -q)
docker rmi $(docker images -q)
```

```
systemctl start zen-node
systemctl start zen-secnodetracker
systemctl start acme-sh
```

This will resolev your disk issues!

**Comment by andrewklau** [comment]
Upgrading can be done by just restarting the service, it will pull the latest version:

```
systemctl restart zen-node
systemctl restart zen-secnodetracker
```

**Comment by dazarn** [comment]
Thanks a lot, it works indeed, so easy! I thought it would be much more troubles :-)

**Comment by phobos777** [comment]
thank you!  this worked on 1/2 of the nodes.    here is the errors i'm getting on the second half of the nodes.   

![image](https://user-images.githubusercontent.com/15862598/41923645-f0795728-7935-11e8-84e6-ebc8b0980659.png)

**Comment by phobos777** [comment]
we can PM if wanted, and i'll give you more details.

**Comment by 333miiko** [comment]
For some reason I'm unable to DM you, says you're not in the same server or
something. Do you have privacy settings blocked?

Can you post the output of:

systemctl status zen-node
systemctl status zen-secnodetracker

What container is that screenshot from?

**Comment by phobos777** [comment]
i found you on discord and put a PM there for you about steps i took.   :)
