### ISSUE TITLE
Super node support?

### ISSUE THREAD

**Issue by slayorktc** [WhenLamboMoon/docker-zen-node#80]
July 19th update will allow for super nodes. Same exact setup as the secure node but at some point it needs to be either secure or super in the install. Does the new tracker version 0.3.0 get pulled into the docker automatically?

**Comment by 333miiko** [comment]
The images should have been updated already to support super nodes.

I'm currently travelling so can't update the installer right now, however you will be able to migrate your secure nodes to super nodes by following their migration.

Just enter into the secure node tracker

```
docker exec -it zen-secnodetracker /bin/bash
node setup.js
# Enter the new T address with 500 ZEN stake
# Enter through the remaining options, assuming no changes are required
# Enter 'super' for the 'node category' prompt
exit
systemctl restart zen-secnodetracker
```

See https://zencash.atlassian.net/wiki/spaces/ZEN/pages/22740994/Migration+from+Secure+Node+to+Super+Node for more info

**Comment by slayorktc** [comment]
Awesome! Thanks for the help! Seems pretty straight forward.

**Comment by 333miiko** [comment]
Support has now been added. 

**IMPORTANT NOTES FOR UPGRADING**

The securenode tracker uses a new configuration meaning if you upgrade it will break.

Two options are:

Re-run the installer again, this will re-generate the new config which is compatible with the latest version (remember to grab the latest version)

Update the config manually

cat << EOF > /mnt/zen/secnode/config.json
{
 "active": "secure",
 "secure": {
  "nodetype": "secure",
  "nodeid": null,
  "servers": [
   "ts2.eu",
   "ts1.eu",
   "ts3.eu",
   "ts4.eu",
   "ts4.na",
   "ts3.na",
   "ts2.na",
   "ts1.na"
  ],
  "stakeaddr": "$stakeaddr",
  "email": "$email",
  "fqdn": "$fqdn",
  "ipv": "4",
  "region": "$region",
  "home": "ts1.$region",
  "category": "none"
 }
}
EOF

Remember to replace all the variables starting with $

**Comment by slayorktc** [comment]
I used your new install script and I saw it created config.json but in the logs I am getting this error:

Jul 17 18:48:34 mn1 systemd[1]: Started Zen Secnodetracker Container.
Jul 17 18:48:35 mn1 docker[9370]: Secure node config found OK - linking...
Jul 17 18:48:36 mn1 docker[9370]: Retrieving zen rpc config....
Jul 17 18:48:36 mn1 docker[9370]: /home/node/secnodetracker/app.js:23
Jul 17 18:48:36 mn1 docker[9370]: if (config.ipv === '6') {
Jul 17 18:48:36 mn1 docker[9370]:            ^
Jul 17 18:48:36 mn1 docker[9370]: TypeError: Cannot read property 'ipv' of undefined
Jul 17 18:48:36 mn1 docker[9370]:     at Object.<anonymous> (/home/node/secnodetracker/app.js:23:12)
Jul 17 18:48:36 mn1 docker[9370]:     at Module._compile (module.js:652:30)
Jul 17 18:48:36 mn1 docker[9370]:     at Object.Module._extensions..js (module.js:663:10)
Jul 17 18:48:36 mn1 docker[9370]:     at Module.load (module.js:565:32)
Jul 17 18:48:36 mn1 docker[9370]:     at tryModuleLoad (module.js:505:12)
Jul 17 18:48:36 mn1 docker[9370]:     at Function.Module._load (module.js:497:3)
Jul 17 18:48:36 mn1 docker[9370]:     at Function.Module.runMain (module.js:693:10)
Jul 17 18:48:36 mn1 docker[9370]:     at startup (bootstrap_node.js:191:16)
Jul 17 18:48:36 mn1 docker[9370]:     at bootstrap_node.js:612:3
