### ISSUE TITLE
New install isn't dropping an image

### ISSUE THREAD

**Issue by phobos777** [WhenLamboMoon/docker-zen-node#83]
@333miiko   yah me again.  :D       when doing a new Secure node, with the most recient image.  it's hanging at this point (see below).  feels like the docker image isn't loading.  and docker ps only adding one docker.   i guess the image isn't coming down?

Skipping adding existing rule (v6)
Skipping adding existing rule
Skipping adding existing rule (v6)
Skipping adding existing rule
Skipping adding existing rule (v6)
Firewall is active and enabled on system startup

## Enabling fail2ban services...

Synchronizing state of fail2ban.service with SysV init with /lib/systemd/systemd-sysv-install...
Executing /lib/systemd/systemd-sysv-install enable fail2ban

## Waiting for node to fetch params ...

Error response from daemon: No such container: zen-node
..
Error response from daemon: No such container: zen-node
..
Error response from daemon: No such container: zen-node
..
Error response from daemon: No such container: zen-node
..
Error response from daemon: No such container: zen-node
..
Error response from daemon: No such container: zen-node
..

and docker ps output:
root@Z20bWLM:~# docker ps
CONTAINER ID        IMAGE               COMMAND              CREATED             STATUS              PORTS               NAMES
6225de404f08        neilpang/acme.sh    "/entry.sh daemon"   4 minutes ago       Up 4 minutes                            acme-sh

**Comment by 333miiko** [comment]
Pushing an update which will fix this

**Comment by phobos777** [comment]
fixed with new image.  yes thank you!
