### ISSUE TITLE
install.sh

### ISSUE THREAD

**Issue by milyway** [WhenLamboMoon/docker-zen-node#84]
I'm trying to install a super node, but cannot go past the first command....

curl -O https://raw.githubusercontent.com/WhenLamboMoon/docker-zen-node/master/install.sh

invokes all the scripts under https://raw.githubusercontent.com/WhenLamboMoon/docker-zen-node/master/install.sh

but when I do 
chmod +x install.sh

it says 
chmod: cannot access 'install.sh' : No such file or directory.

I'd greatly appreciate it if anyone could help me go past this.
Thank you very much.

**Comment by milyway** [comment]
I figured out you might need to change the directory to docker-zen-node

so I did 
cd docker-zen-node 

and was able to run
chmod +x install.sh

but when I do
./install.sh <stakeaddr> <email> <fqdn> <region> <nodetype>
and put all info including super in the nodetype

it says
Execution format ./install.sh stakeaddr email fqdn region nodetype

and nothing happens afterwards.

I'd greatly appreciate it if anyone could help me go past this.
Thank you very much.

**Comment by 333miiko** [comment]
Can you edit line 11 and change it to:

```
if [ $# -ne 5 ]; then
```

That should fix your problem

**Comment by 333miiko** [comment]
Please use the latest installer file (download it again), it will fix your problem.

**Comment by milyway** [comment]
I've downloaded the latest file again, (the one with line#11 if [ $# -lt 4 ]; then )
but same thing happens, 
it still says
Execution format ./install.sh stakeaddr email fqdn region nodetype

and nothing happens afterwards...

**Comment by 333miiko** [comment]
Do you have something like:

```
./install.sh znoYaPU2G7MzUA69cMSYzmqMG4rkw3Mx7ac test@gmail.com test6.example.com na secure
```

**Comment by milyway** [comment]
./install.sh znajbMpS791HWYrbwqSMKQJt32Ux2u1AGT6 yousukchoi@hotmail.com zensuper01.masternodevps.net na super
