### ISSUE TITLE
NO FQDN

### ISSUE THREAD

**Issue by phobos777** [WhenLamboMoon/docker-zen-node#86]
I"m getting a no FQDN from time to time. and then the Cert is marked as "not check" or "false".   i've been rerunning the install.sh and that works sometimes but not all the time.  here is the log:

2018-07-19 16:21:42 UTC -- Clearing timer
2018-07-19 16:22:49 UTC -- No FQDN found. Please check the hostname and rerun setup to enter it.
2018-07-19 16:23:21 UTC -- Stat check: connected to:ts1.na blocks:344735  peers:8  bal:0.5596  isValidBal:false  queueDepth:0  lastChalBlock:344731  lastExecSec:174.23

**Comment by phobos777** [comment]
oh and i do have the A record and the FQDN as the DNS hosting website with the right IP address.  (IPV4 with Secure nodes by the way)

**Comment by phobos777** [comment]
Visual from the website as well

![image](https://user-images.githubusercontent.com/15862598/42957711-7ae188cc-8b51-11e8-97ca-d94f09457bf2.png)

**Comment by slayorktc** [comment]
Bump for fix. Been banging my head against this all day.

**Comment by phobos777** [comment]
Cert issue still exists after lastest image from 7/20/18.  :(   here is an output.   AND notice a new error in debug.log.  (wonder about this TLS error).  see below:  

2018-07-20 09:58:19 UTC -- Stats received by ts1.na
2018-07-20 10:02:10 UTC -- No FQDN found. Please check the hostname and rerun setup to enter it.
2018-07-20 10:02:11 UTC -- Exception: Certificate issue - no hostname

debug.log. (and that isn't my IP address. just a connection attempt)
2018-07-20 09:26:27 ERROR: AcceptToMemoryPool: joinsplit requirements not met
2018-07-20 09:26:35 TLS: ERROR: ./zen/tlsmanager.cpp: accept: TLS connection from 142.44.166.8:49436 failed
2018-07-20 09:26:48 ERROR: AcceptToMemoryPool: joinsplit requirements not met

**Comment by phobos777** [comment]
and adding:   sudo add-apt-repository universe

**Comment by slayorktc** [comment]
Nice work! In my debugging effort I tried to run certbot but apt didn't have it in the regular repo so I gave up..

I ended up just deleting everything inside the certs directory then modifying the install script to just run the cert generation again. What is strange is I had already did this way earlier in my troubleshooting but only added a --force to the docker exec command, which I saw in the log generated new certs so I wrote that off as it's not the certs... But after just blowing away everything in the directory and rerunning the cert passed again... That was an interesting bug you work through.... Glad it's working for both of us again!

**Comment by phobos777** [comment]
I fixed 6 nodes and two still have issues with it, so it’s not 100% , but some better than none?   We’ll see if @333miiko can work his magic

**Comment by slayorktc** [comment]
Are those super nodes or secure? All my secure nodes came right through deleting the certs dir and running the install again.

**Comment by slayorktc** [comment]
I am currently having an issue with a super node running challenges.. Not sure whats going on with it.. Again another strange error....

**Comment by phobos777** [comment]
I’m talking about secure nodes . But challenges are still a problem with both

**Comment by slayorktc** [comment]
Yeah. Getting so much flake in the discord for using docker.. phew.. like 5 people commented about it.. :D

**Comment by 333miiko** [comment]
Sorry for the delay guys, I'm still travelling until the end of the month. Trying to get as much time in as possible to help fix this config update.

certbot is a replacement for acme.sh which is meant to be better for the renewal. When I'm back I'll get certbot integrated with the installer and have it handle the updates and clearing of images automatically.

**Comment by 333miiko** [comment]
@slayorktc @phobos777 new update with certbot, please let me know how this goes

https://github.com/WhenLamboMoon/docker-zen-node/commit/b1037d4f8182f173937f9fd459fab39708722308
