### ISSUE TITLE
Config.json permission error; after image update on 7/20/18

### ISSUE THREAD

**Issue by phobos777** [WhenLamboMoon/docker-zen-node#88]
@333miiko    Hi,  please add 'execute permissions' on config.json.   Repeat process, while running new image, then looking at secure node image i get:  

 Authenticated.
{ Error: EACCES: permission denied, open './config/config.json'
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: './config/config.json' }
2018-07-20 09:51:53 UTC -- Could not save nodeid=123334 { Error: EACCES: permission denied, open './config/config.json'
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: './config/config.json' }
2018-07-20 09:51:53 UTC -- Saved nodeid=123334

**Comment by 333miiko** [comment]
You shouldn't need executive permission to access the file. Did you create the new config file using the manual method or was it a fresh install? I tested this through a fresh install and it doesn't need the execution permission.

**Comment by Spiral11** [comment]
I setup 10 new nodes last night using this script and 3 of them encountered the above error. No idea why the other 7 didn't.

I just did chmod 777 on config.json & restarted tracker to fix it.

**Comment by 333miiko** [comment]
https://github.com/WhenLamboMoon/docker-zen-node/commit/32b89a6bc23361381f2bf3fb33b211568b31c259
