### ISSUE TITLE
challenges don't seem to work.

### ISSUE THREAD

**Issue by slayorktc** [WhenLamboMoon/docker-zen-node#89]
could not get block hash from zend

https://supernodes1.na.zensystem.io/nodes/4858/chals

**Comment by slayorktc** [comment]
The zend daemon and tracker must have the same ip addresses

This was from psyrax on the discord... He says we should run the zend and secnodetracker in the same container.. How do we get around this?

**Comment by slayorktc** [comment]
Your zend daemon has a different ip to your tracker
This is to stop people using a single zend daemon and multiple trackers

**Comment by phobos777** [comment]
It’s up to @333miiko however if he drops using docker that would fix the ip problems. I know Dicker is WLMs trademark approach though :)

**Comment by slayorktc** [comment]
I don't mind docker.. I think it makes deploying a breeze. So quick.. Debugging is a pain... But for super nodes, I guess they have an additional requirement that both need the same ip? I assume local ip? Because external they should both be the same.

**Comment by slayorktc** [comment]
Most likely need him to chime in because I don't have a clue how to tie the ips of two containers together or to place the tracker inside the container with the daemon. Id personally prefer to keep them separate but if thats not going to work...

**Comment by slayorktc** [comment]
I think I found the answer but not sure how to implement it.
kjtanaka
Koji Tanaka
1 
Mar '16
Hi Long,

Have you found a way to make that happen? You can create a new network with --driver bridge option and attach it to one of your network interfaces(e.g. eth1). Here’s an example:

# Delete the IP address from eth1
$ sudo ip addr del 192.168.33.10/24 dev eth1

# Create "shared_nw" with a bridge name "docker1"
$ sudo docker network create \
    --driver bridge \
    --subnet=192.168.33.0/24 \
    --gateway=192.168.33.10 \
    --opt "com.docker.network.bridge.name"="docker1" \
    shared_nw

# Add docker1 to eth1
$ sudo brctl addif docker1 eth1
After setting the bridge, you can run a container like this.

$ docker run --name container1 --net shared_nw --ip 192.168.33.11 -dt ubuntu
$ ping -c 3 192.168.33.11
I have a more detailed explanation on my github repo. Here’s the link if you’re interested.
https://github.com/kjtanaka/docker-example-shared-nw 1.3k

**Comment by slayorktc** [comment]
Wait I noticed that the docker command is setting --net=host.. Which I assume bridges all the containers together anyways..

ExecStart=/usr/bin/docker run --rm --net=host -v /mnt/zen:/mnt/zen


Not sure why the tracker is having issues running the challenges..

**Comment by slayorktc** [comment]
Closing this. Ended up getting everything up and running with just doing some -rescans and such. No code change needed.
