### ISSUE TITLE
No issue just questions

### ISSUE THREAD

**Issue by slayorktc** [WhenLamboMoon/docker-zen-node#9]
Not sure how to message you besides making an issue.

Couple questions.

Are you having challenge fails? Which VPS are you using? 1core/2gb of ram + swap?

Would increase the amount of swap from 4g to 6gm help reduce challenge times?

**Comment by 333miiko** [comment]
hey @slayorktc I hangout on zencash slack sometimes but mostly on [thecryptosyndicate slack](https://thecryptosyn.herokuapp.com/) if you want to reach me faster feel free to pm me there.

1 core/2gb ran fine for me, what provider did you end up using? You need a minimum of 4GB ram to be able to process the challenges, obviously if you can run with more ram it'll be faster.

**Comment by slayorktc** [comment]
I am trying out linode, vultr, and ovh. Linode one of the 2 nodes keeps getting over 300 every couple days. Not sure why. You mean minimum 4gb including swap, correct? What about 6gb of swap vs 4gb. Could help reduce the times?

**Comment by 333miiko** [comment]
Yeah the minimum was 4GB swap. There would be a number of reasons, most likely CPU or the shared SSD is getting heavy writes, sadly the swap space is ultimately the bottleneck

**Comment by 333miiko** [comment]
I found I got the best performance from alibabacloud but that might be because it is new

**Comment by slayorktc** [comment]
Sweet! I'll give them a shot. Thanks for the help.

**Comment by slayorktc** [comment]
I am trying out alibabcloud but getting this issue when I run the installer:

[Thu Nov 30 06:06:13 UTC 2017] znode20.convergegroup.tech:Verify error:Fetching http://znode20.convergegroup.tech/.well-known/acme-challenge/K_lUJcVruHodaIqpSopamt8ec-EAwAYxvXWNmL4Deu8: Timeout
[Thu Nov 30 06:06:13 UTC 2017] Please add '--debug' or '--log' to check more details.

Didn't see that message before on vultr, linode or ovh. Do you know how to resolve it?

**Comment by 333miiko** [comment]
When you use alibabacloud you need to open the ports, they have another firewall that is blocking access. You will want to open

tcp 22
tcp 80
tcp 443
tcp 9033
tcp 19033

**Comment by slayorktc** [comment]
Sweet that worked! I opened both inbound and outbound. Do I need both or just one of the two ways?

**Comment by slayorktc** [comment]
When were you going to update to mainnet? Next couple days?

**Comment by 333miiko** [comment]
You only need to open inbound. I will update it to mainnet shortly after I run some tests.

**Comment by 333miiko** [comment]
I've updated the code so you should now be able to deploy to mainnet now :)

**Comment by slayorktc** [comment]
Very cool! :) I will give it a shot shortly

**Comment by 333miiko** [comment]
Just note mainnet isn't up yet, I think there's a maintenance for another 2 more hours.

**Comment by 333miiko** [comment]
I have deployed a few nodes on mainnet now without any issues, this should be good to go :)

**Comment by slayorktc** [comment]
Thanks for all the hard work. Just pulled down the latest version and everything seems to running smooth. I sent 1zen to your donation address. Thanks again!

**Comment by 333miiko** [comment]
No worries, thanks :)

**Comment by slayorktc** [comment]
Which hardware did you go with on Alibaba? I went with the $5 plan but the vps keeps locking up with 100% cpu utilization and I get secnode emails about being down every 5 minutes. Trying out 4 other providers all with the same specs and they aren't having that issue. How is your vps running?

**Comment by 333miiko** [comment]
I have some special promo I got with alibaba so it's a bit beefier then the $5 plan. For my new nodes I'm using OVH ssd2 this has given me the best results.

**Comment by slayorktc** [comment]
Okay. Yeah ovh ssd2 is giving me the best results as well. I don't think the $5 alibaba can handle it. I will swap it over. Thanks!

**Comment by slayorktc** [comment]
How do I go about running zend with -reindex? Should I go inside the docker with a exec /bin/bash? Or change the Dockerfile to cmd [zend -reindex]?

**Comment by 333miiko** [comment]
Do you only need to run it once? If so then you will need to stop the existing zend process first, try this:

```
systemctl stop zen-node
docker run --rm --net=host -p 9033:9033 -p 18231:18231 -v /mnt/zen:/mnt/zen --name zen-node --entrypoint=/bin/bash whenlambomoon/zend:latest

zend -reindex
# control+c to exit after its done
systemctl restart zen-node
```

**Comment by slayorktc** [comment]
Giving it a shot. Looks like it is resyncing. Hopefully that fixes the issue I was having.

Thanks.

**Comment by 333miiko** [comment]
Let me know how it goes. 

btw what issues were you having?

**Comment by slayorktc** [comment]
I tried out ovh SSD 1 and last night the node went down because the 10gb SSD filled up 100%. I upgraded but now zen-node has errors and suggests doing a reindex. Not an issue with your code. 😃

**Comment by 333miiko** [comment]
Okies, glad you got it all resolved. You could also just delete the /mnt/zen/config/{blocks,chainstate,database} folder and let it resync if the reindex doesn't work.

**Comment by andrewklau** [comment]
Btw if you have to reindex again I updated the README with instructions for doing a reindex:

```
systemctl stop zen-node
docker run --rm --net=host -p 9033:9033 -p 18231:18231 -v /mnt/zen:/mnt/zen --name zen-node whenlambomoon/zend:latest zend -reindex
```

**Comment by 333miiko** [comment]
systemctl stop zen-node
docker run --rm --net=host -p 9033:9033 -p 18231:18231 -v /mnt/zen:/mnt/zen --name zen-node whenlambomoon/zend:latest zend -reindex

**Comment by slayorktc** [comment]
Thanks. Got the node all synced up and running smooth. :)

**Comment by 333miiko** [comment]
Did you try

```
docker run --rm --net=host -p 9033:9033 -p 18231:18231 -v /mnt/zen:/mnt/zen -v /etc/letsencrypt/:/etc/letsencrypt --name zen-node whenlambomoon/zend:latest zend -reindex
```

**Comment by slayorktc** [comment]
Sort of. I am getting challenge errors and the discord admins told me to run -rescan to fix. 

Here is my command, slightly different from yours.

docker run --rm --net=host -p 9033:9033 -p 18231:18231 -v /mnt/zen:/mnt/zen -v /etc:/etc -v /home/mns:/home/user --name zen-node whenlambomoon/zend:latest zend -rescan


I needed to add /home/mns:/home/user because it gave this error without it.
chown: cannot access '/home/user': No such file or directory

**Comment by slayorktc** [comment]
But then it just hangs here:

Starting with UID/GID : 9001/9001
Symlinking external zcash-params volume...
Using external data volume
Copying additional trusted SSL certificates
Clearing symlinks in /etc/ssl/certs...
done.
Updating certificates in /etc/ssl/certs...
149 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.
Zcash - fetch-params.sh

Zen uses the same zkSNARK parameters generated by ZCash.
This script will fetch the Zcash zkSNARK parameters and verify their
integrity with sha256sum.

If they already exist locally, it will exit now and do nothing else.
Starting zend -rescan ..


Been here for 8 hours. Admin said it took him 1.5 to run it.

**Comment by 333miiko** [comment]
You shouldn't need to mount any home directory

**Comment by 333miiko** [comment]
```
docker run --rm --net=host -p 9033:9033 -p 18231:18231 -v /mnt/zen:/mnt/zen -v /etc/letsencrypt/:/etc/letsencrypt --name zen-node whenlambomoon/zend:latest zend -rescan
```

**Comment by slayorktc** [comment]
command is running. But not sure if it is working. Or will just hang. It is here:

Starting with UID/GID : 9001/9001
Symlinking external zcash-params volume...
Using external data volume
Copying additional trusted SSL certificates
Clearing symlinks in /etc/ssl/certs...
done.
Updating certificates in /etc/ssl/certs...
149 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.
Zcash - fetch-params.sh

Zen uses the same zkSNARK parameters generated by ZCash.
This script will fetch the Zcash zkSNARK parameters and verify their
integrity with sha256sum.

If they already exist locally, it will exit now and do nothing else.
Starting zend -rescan ..


The admins said that you can run the getinfo command and it will say that it is rescanning but not sure how to run that while running this other command. Or how to go inside the container and check that.

**Comment by 333miiko** [comment]
In another terminal window:

```
docker exec -it zen-node bash
```

**Comment by slayorktc** [comment]
Thanks for the info.

Doesn't look like it is scanning. Not sure if thats on our side or zens side.

root@zen:/# gosu user zen-cli getinfo
{
  "version": 2001650,
  "protocolversion": 170002,
  "walletversion": 60000,
  "balance": 0.00000000,
  "blocks": 447932,
  "timeoffset": 0,
  "connections": 8,
  "proxy": "",
  "difficulty": 2748314.342755821,
  "testnet": false,
  "keypoololdest": 1534903622,
  "keypoolsize": 101,
  "paytxfee": 0.00000000,
  "relayfee": 0.00000100,
  "errors": ""
}
root@zen:/#
