### ISSUE TITLE
in new install 'external ip' not filling out correctly

### ISSUE THREAD

**Issue by phobos777** [WhenLamboMoon/docker-zen-node#91]
results from the secure node tracker when it first installs

Secure node config found OK - linking...
Retrieving zen rpc config....
External IP address (externalip=) not found in zen.conf. At least one (IPv4 or IPv6) required for secure nodes. Both IPv4 and IPv6 required for super nodes.
If multiple, add the externalip= for each address on a separate line.

**Comment by 333miiko** [comment]
It will pick based on the dns response from your fqdn, so if your fqdn does not have the dns records setup then no externalip will be filled

**Comment by phobos777** [comment]
eek!  :)  i can ping my FQDN and that is working correctly.  i'll keep testing

**Comment by phobos777** [comment]
@333miiko   okay here is the Answer:   i'm setting up a Secure node.   HOWEVER, i must put both the IP4 and the IP6 (compressed) in there as two lines of External IP's.    (secure nodes only need IP4,  Super nodes require both).  but when doing the script. the Secure node tracker won't start unless BOTH IP4 and IPv6 is there.

**Comment by 333miiko** [comment]
The installer should pick both your ipv4 and ipv6 addresses from whatever your fqdn resolves to.

**Comment by phobos777** [comment]
install only adds on external ip for the secure nodes.   however tracker was looking for two external ip lines

**Comment by phobos777** [comment]
i moved passed it, but wanted you to know for new installs  :)

**Comment by 333miiko** [comment]
it will add as many as your dns server returns, so if you have multiple ipv4 addresses and 1 ipv6 address it will pick that up

**Comment by phobos777** [comment]
OOOHHHH,   okay.  i only added an A record for IPv4.   i didn't add a AAAA for IPv6,  (but i didn't think i needed to for secure nodes;  thanks for the clarification
