### ISSUE TITLE
One node don't want to install...

### ISSUE THREAD

**Issue by darkoopa** [WhenLamboMoon/docker-zen-node#95]
Hello, sorry for the many questions this weeks ^^
I just added 2 more nodes.
They have the same OVH VPS, the 42 zen are both on my ledger nano S, I use the same command to install.

But one is working, for the other, impossible to install :

> ## Waiting for node to fetch params ...
> 
> error: couldn't connect to server: unknown (code -1)
> (make sure server is running and you are connecting to the correct RPC port)

I tried the insall many times, I completely reseted the VPS for a clean install twice, every time it does that. I don't understand as the other one is online right now...

thx

best regards

**Comment by 333miiko** [comment]
Is that the full and final error message, does it hang here?

**Comment by darkoopa** [comment]
It will repeat this message dozens of time

**Comment by cgaspart** [comment]
> Hello, sorry for the many questions this weeks ^^
> I just added 2 more nodes.
> They have the same OVH VPS, the 42 zen are both on my ledger nano S, I use the same command to install.
> 
> But one is working, for the other, impossible to install :
> 
> > ## Waiting for node to fetch params ...
> > error: couldn't connect to server: unknown (code -1)
> > (make sure server is running and you are connecting to the correct RPC port)
> 
> I tried the insall many times, I completely reseted the VPS for a clean install twice, every time it does that. I don't understand as the other one is online right now...
> 
> thx
> 
> best regards

Same here
