### ISSUE TITLE
on new image externalip= (blank)

### ISSUE THREAD

**Issue by phobos777** [WhenLamboMoon/docker-zen-node#96]
on new image with new install.sh downloaded today.  doing secure nodes, it installs and comes up and says 'can't find zen-node'.  looking at the details in the zen.conf the "externalip=" is blank stated as such.  adding my ip and rebooting moves it forward.   please fix when you have a moment.  thanks!

**Comment by 333miiko** [comment]
This is the same as we discussed before, externalip comes from your DNS.

If you don't set your DNS and can't resolve it from your VPS it will come up as blank.

**Comment by 333miiko** [comment]
```
dig $fqdn A $fqdn AAAA +short
```

**Comment by phobos777** [comment]
apologies! your right we did talk about this.   i do have my A record DNS correct for the Secure node.  wonder if i have to load up both A and AAAA in DNS (and not just the A record).  but for secure node only requiring A record.   i'll play around more with it.
