### ISSUE TITLE
(small thing).   automate in install.sh

### ISSUE THREAD

**Issue by phobos777** [WhenLamboMoon/docker-zen-node#97]
when running:   curl -O https://raw.githubusercontent.com/WhenLamboMoon/docker-zen-node/master/install.sh

would be nice to have these two things automated.  i say "yes" in both cases; and install completes fine:  (see pics inserted)

![image](https://user-images.githubusercontent.com/15862598/43518978-c21bfb78-955b-11e8-8ce1-4c7234a4c357.png)

![image](https://user-images.githubusercontent.com/15862598/43519008-d5893ce8-955b-11e8-8e19-916cf1a5ee89.png)

**Comment by 333miiko** [comment]
It's better to avoid clobbering incase someone had made things like custom cloud.cfg as part of their install.
