### ISSUE TITLE
nodetype not set to secure if it is not provided

### ISSUE THREAD

**Issue by jurgis** [WhenLamboMoon/docker-zen-node#99]
Just installed a new node and run into several issues.
One of them was that if the last argument for install.sh was not provided nodetype was empty
leading to invalid config file and other errors.

I assume the idea was if it is omitted it will be **secure**.
In that case please make a small adjustment for example from:

```bash
if [ -z "$5" ]; then
  nodetype=${5}
else
  nodetype="secure"
fi
```

to:
```bash
if [ -z "$5" ]; then
  nodetype="secure"
else
  nodetype=${5}
fi
```

or something similar which would set nodetype in case `${5}` is not set.

**Comment by 333miiko** [comment]
https://github.com/WhenLamboMoon/docker-zen-node/commit/8606db81b1a5f010475a2b67344d26bb70088f49
